<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/MphRead/Mods/ThumbnailBatch.cs" Link="ThumbnailBatch.cs" />
  </ItemGroup>
</Project>
