#pragma once

// Generated by tools/gen-weapon-metadata.py from
// src/MphRead/Metadata/Weapons.cs.  Do not edit by hand.
//
// One record per weapon, with the same fields the managed
// WeaponInfo carries.  The compact accessors in Weapons.cpp read
// out of this rather than out of a second, shorter table.

#include "Formats/Types.hpp"
#include "Metadata/weapon_metadata.hpp"

#include <array>
#include <cstdint>
#include <string_view>

namespace fruityprime::metadata {

// The enums the managed table names live in their own counterparts;
// naming them here keeps the generated rows reading like the C# ones.
using formats::Affliction;
using formats::BeamType;
using weapon_table::WeaponFlags;

struct WeaponRecord {
    std::string_view description{};
    BeamType beam{};
    BeamType beam_kind{};
    std::array<std::uint8_t, 2> draw_func_ids{};
    std::array<std::uint16_t, 2> colors{};
    std::uint8_t priority{};
    WeaponFlags flags{};
    std::uint16_t splash_damage{};
    std::uint16_t min_charge_splash_damage{};
    std::uint16_t charged_splash_damage{};
    std::array<std::uint8_t, 2> splash_damage_types{};
    std::uint8_t shot_cooldown{};
    std::uint8_t autofire_cooldown{};
    std::uint8_t ammo_type{};
    std::array<std::uint8_t, 2> collision_effects{};
    std::array<std::uint8_t, 2> muzzle_effects{};
    std::array<std::uint8_t, 2> dmg_dir_types{};
    std::array<std::uint8_t, 2> damage_interpolations{};
    std::array<Affliction, 2> afflictions{};
    std::uint8_t padding21{};
    std::uint16_t min_charge{};
    std::uint16_t full_charge{};
    std::uint16_t ammo_cost{};
    std::uint16_t min_charge_cost{};
    std::uint16_t charge_cost{};
    std::uint16_t uncharged_damage{};
    std::uint16_t min_charge_damage{};
    std::uint16_t charged_damage{};
    std::uint16_t headshot_damage{};
    std::uint16_t min_charge_headshot_damage{};
    std::uint16_t charged_headshot_damage{};
    std::uint16_t uncharged_lifespan{};
    std::uint16_t min_charge_lifespan{};
    std::uint16_t charged_lifespan{};
    std::array<std::uint16_t, 2> speed_decay_times{};
    std::uint16_t padding42{};
    std::array<std::uint16_t, 2> speed_interpolations{};
    std::int32_t uncharged_dmg_dir_mag{};
    std::int32_t min_charge_dmg_dir_mag{};
    std::int32_t charged_dmg_dir_mag{};
    std::int32_t zoom_fov{};
    std::int32_t uncharged_cyl_radius{};
    std::int32_t min_charge_cyl_radius{};
    std::int32_t charged_cyl_radius{};
    std::int32_t uncharged_speed{};
    std::int32_t min_charge_speed{};
    std::int32_t charged_speed{};
    std::int32_t uncharged_final_speed{};
    std::int32_t min_charge_final_speed{};
    std::int32_t charged_final_speed{};
    std::int32_t uncharged_gravity{};
    std::int32_t min_charge_gravity{};
    std::int32_t charged_gravity{};
    std::int32_t uncharged_homing{};
    std::int32_t min_charge_homing{};
    std::int32_t charged_homing{};
    std::int32_t homing_range{};
    std::int32_t homing_tolerance{};
    std::int32_t uncharged_splash_radius{};
    std::int32_t min_charge_splash_radius{};
    std::int32_t charged_splash_radius{};
    std::int32_t uncharged_distance{};
    std::int32_t min_charge_distance{};
    std::int32_t charged_distance{};
    std::int32_t uncharged_spread{};
    std::int32_t min_charge_spread{};
    std::int32_t charged_spread{};
    std::int32_t uncharged_rico_loss_h{};
    std::int32_t min_charge_rico_loss_h{};
    std::int32_t charged_rico_loss_h{};
    std::int32_t uncharged_rico_loss_v{};
    std::int32_t min_charge_rico_loss_v{};
    std::int32_t charged_rico_loss_v{};
    std::uint8_t projectile_count{};
    std::uint8_t min_charge_projectile_count{};
    std::uint8_t charge_projectile_count{};
    std::uint16_t smoke_start{};
    std::uint16_t smoke_minimum{};
    std::uint16_t smoke_drain{};
    std::uint16_t smoke_shot_amount{};
    std::uint16_t smoke_charge_amount{};
};

} // namespace fruityprime::metadata
