PORT_BOUNDARY_SOURCES := \
    $(CPP_ROOT)/Export/Collada.cpp \
    $(CPP_ROOT)/Export/Images.cpp \
    $(CPP_ROOT)/Formats/AiPersonality.cpp \
    $(CPP_ROOT)/Formats/Collision.cpp \
    $(CPP_ROOT)/Formats/collision_runtime.cpp \
    $(CPP_ROOT)/Formats/CollisionDetection.cpp \
    $(CPP_ROOT)/Formats/EntityClass.cpp \
    $(CPP_ROOT)/Formats/FhSound.cpp \
    $(CPP_ROOT)/Formats/sound_export.cpp \
    $(CPP_ROOT)/Formats/effect_funcs.cpp \
    $(CPP_ROOT)/Formats/effect_particle_funcs.cpp \
    $(CPP_ROOT)/Formats/Model.cpp \
    $(CPP_ROOT)/Formats/movie_playback.cpp \
    $(CPP_ROOT)/Formats/NodeData.cpp \
    $(CPP_ROOT)/Formats/RawFormats.cpp \
    $(CPP_ROOT)/Metadata/SoundMeta.cpp \
    $(CPP_ROOT)/Metadata/metadata_lookup.cpp \
    $(CPP_ROOT)/Mods/ConsoleWindow.cpp \
    $(CPP_ROOT)/Mods/DebugLog.cpp \
    $(CPP_ROOT)/Mods/ScreenCapture.cpp \
    $(CPP_ROOT)/Mods/ShutdownSignals.cpp \
    $(CPP_ROOT)/Mods/SpectatorMode.cpp \
    $(CPP_ROOT)/Mods/ThumbnailCapture.cpp \
    $(CPP_ROOT)/Mods/WindowMode.cpp \
    $(CPP_ROOT)/Mods/WorldEvents.cpp \
    $(CPP_ROOT)/Mods/Chat/ChatBox.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/DemoPickerView.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/GuiLauncher.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/HomeView.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/HomeWindow.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/KeyRow.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/MapPickerView.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/MenuEntry.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/PadRow.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/PauseMenuView.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/PauseMenuWindow.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/ProgressRow.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/Rows.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/ServerRow.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/SettingsView.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/SettingsWindow.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/SliderRow.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/SplashView.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/TrackedText.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/UiCapture.cpp \
    $(CPP_ROOT)/Mods/Launcher/Gui/UpdateBadge.cpp \
    $(CPP_ROOT)/Mods/Launcher/Portable/AdventureSave.cpp \
    $(CPP_ROOT)/Mods/Launcher/Portable/GameFiles.cpp \
    $(CPP_ROOT)/Mods/Launcher/Portable/LauncherPrefs.cpp \
    $(CPP_ROOT)/Mods/Launcher/Portable/LaunchPlan.cpp \
    $(CPP_ROOT)/Mods/Launcher/Portable/MatchStart.cpp \
    $(CPP_ROOT)/Mods/Launcher/Portable/SetupProgress.cpp \
    $(CPP_ROOT)/Mods/Launcher/Portable/TextLauncher.cpp \
    $(CPP_ROOT)/Mods/MapGen/BuiltMap.cpp \
    $(CPP_ROOT)/Mods/MapGen/CustomRooms.cpp \
    $(CPP_ROOT)/Mods/MapGen/MapBuilder.cpp \
    $(CPP_ROOT)/Mods/MapGen/MapBundle.cpp \
    $(CPP_ROOT)/Mods/MapGen/MapCollisionPacker.cpp \
    $(CPP_ROOT)/Mods/MapGen/MapDefinition.cpp \
    $(CPP_ROOT)/Mods/MapGen/MapNodePacker.cpp \
    $(CPP_ROOT)/Mods/MapGen/MapPacker.cpp \
    $(CPP_ROOT)/Mods/MapGen/MapReport.cpp \
    $(CPP_ROOT)/Mods/MapGen/MapTextureBake.cpp \
    $(CPP_ROOT)/Mods/MapGen/MapTexturePack.cpp \
    $(CPP_ROOT)/Mods/MapGen/Q3Bsp.cpp \
    $(CPP_ROOT)/Mods/MapGen/Q3Convert.cpp \
    $(CPP_ROOT)/Mods/MapGen/Q3Import.cpp \
    $(CPP_ROOT)/Mods/MapGen/RawStructs.cpp \
    $(CPP_ROOT)/Mods/MapGen/RepackAccess.cpp \
    $(CPP_ROOT)/Mods/Network/DedicatedServer.cpp \
    $(CPP_ROOT)/Mods/Network/DemoFile.cpp \
    $(CPP_ROOT)/Mods/Network/DemoInfo.cpp \
    $(CPP_ROOT)/Mods/Network/DemoLibrary.cpp \
    $(CPP_ROOT)/Mods/Network/DemoPlayback.cpp \
    $(CPP_ROOT)/Mods/Network/DemoRecorder.cpp \
    $(CPP_ROOT)/Mods/Network/MapAudit.cpp \
    $(CPP_ROOT)/Mods/Network/MapRotation.cpp \
    $(CPP_ROOT)/Mods/Network/MechanicsDump.cpp \
    $(CPP_ROOT)/Mods/Network/NetCheckClient.cpp \
    $(CPP_ROOT)/Mods/Network/NetFeatureCheck.cpp \
    $(CPP_ROOT)/Mods/Network/NetProtocol.cpp \
    $(CPP_ROOT)/Mods/Network/NetTransport.cpp \
    $(CPP_ROOT)/Mods/Render/EsBindings.cpp \
    $(CPP_ROOT)/Mods/Render/EsShaders.cpp \
    $(CPP_ROOT)/Mods/Render/GlEs.cpp \
    $(CPP_ROOT)/Mods/Render/PlayerEntityIconBounds.cpp \
    $(CPP_ROOT)/Mods/Sound/AlEs.cpp \
    $(CPP_ROOT)/Mods/Sound/SfxMixer.cpp \
    $(CPP_ROOT)/Mods/Update/BuildVersion.cpp \
    $(CPP_ROOT)/Mods/Update/SyncHttp.cpp \
    $(CPP_ROOT)/Mods/Update/UpdateCheck.cpp \
    $(CPP_ROOT)/Mods/Update/UpdateDownload.cpp \
    $(CPP_ROOT)/Mods/Update/Updater.cpp \
    $(CPP_ROOT)/Sound/Sfx.cpp \
    $(CPP_ROOT)/Testing/TestEffects.cpp \
    $(CPP_ROOT)/Testing/TestLogic.cpp \
    $(CPP_ROOT)/Testing/TestMisc.cpp \
    $(CPP_ROOT)/Testing/TestOverlay.cpp \
    $(CPP_ROOT)/Testing/TestParse.cpp \
    $(CPP_ROOT)/Testing/TestPlayer.cpp \
    $(CPP_ROOT)/Testing/TestPrint.cpp \
    $(CPP_ROOT)/Testing/TestWeapons.cpp \
    $(CPP_ROOT)/Utility/Analyzer.cpp \
    $(CPP_ROOT)/Utility/Archive.cpp \
    $(CPP_ROOT)/Utility/Console.cpp \
    $(CPP_ROOT)/Utility/Extract.cpp \
    $(CPP_ROOT)/Utility/RepackCollision.cpp \
    $(CPP_ROOT)/Utility/RepackEntity.cpp \
    $(CPP_ROOT)/Utility/RepackModel.cpp
