#pragma once

// Generated by tools/gen-ai-dispatch.py from
// src/MphRead/Entities/Players/PlayerAi.cs.  Do not edit by hand.
//
// PlayerAi.ExecuteFuncs1, ExecuteFuncs2 and ExecuteFuncs4 as case
// tables: which behaviour each identifier runs.  The managed
// dispatchers use C# range patterns, which are expanded here so a
// value in the middle of a range cannot go missing.

#include <cstdint>

namespace fruityprime::players::ai_dispatch {

// A behaviour is named by its index in the list below; 0 means the
// identifier runs nothing, which is a real case rather than a hole.
enum class Behavior : std::uint8_t { None = 0 };

// ExecuteFuncs1: 84 identifiers, 84 distinct behaviours.
inline constexpr const char* funcs1_names[] = {
    "",  // 0: runs nothing
    "Func1_2148D50",  // 1
    "Func1_2148DE8",  // 2
    "Func1_2148DF8",  // 3
    "Func1_2148E54",  // 4
    "Func1_2148E64",  // 5
    "Func1_2148E74",  // 6
    "Func1_2148E88",  // 7
    "Func1_2148E98",  // 8
    "Func1_2148EA8",  // 9
    "Func1_2148EB8",  // 10
    "Func1_2148ECC",  // 11
    "Func1_2148EDC",  // 12
    "Func1_2148F10",  // 13
    "Func1_2149034",  // 14
    "Func1_2149088",  // 15
    "Func1_2149094",  // 16
    "Func1_21490AC",  // 17
    "Func1_21490C4",  // 18
    "Func1_21490DC",  // 19
    "Func1_21490F4",  // 20
    "Func1_214910C",  // 21
    "Func1_2149124",  // 22
    "Func1_214913C",  // 23
    "Func1_2149154",  // 24
    "Func1_214916C",  // 25
    "Func1_2149184",  // 26
    "Func1_214919C",  // 27
    "Func1_21491B4",  // 28
    "Func1_21491CC",  // 29
    "Func1_21491E4",  // 30
    "Func1_21491FC",  // 31
    "Func1_214920C",  // 32
    "Func1_214921C",  // 33
    "Func1_214922C",  // 34
    "Func1_214923C",  // 35
    "Func1_214924C",  // 36
    "Func1_214925C",  // 37
    "Func1_214926C",  // 38
    "Func1_214927C",  // 39
    "Func1_214928C",  // 40
    "Func1_214929C",  // 41
    "Func1_21492AC",  // 42
    "Func1_21492BC",  // 43
    "Func1_21492CC",  // 44
    "Func1_21492DC",  // 45
    "Func1_21492EC",  // 46
    "Func1_214932C",  // 47
    "Func1_2149360",  // 48
    "Func1_21493A0",  // 49
    "Func1_21493D4",  // 50
    "Func1_2149414",  // 51
    "Func1_2149448",  // 52
    "Func1_2149488",  // 53
    "Func1_21494BC",  // 54
    "Func1_21494FC",  // 55
    "Func1_2149530",  // 56
    "Func1_2149570",  // 57
    "Func1_21495A4",  // 58
    "Func1_21497F0",  // 59
    "Func1_2149824",  // 60
    "Func1_2149A64",  // 61
    "Func1_2149A98",  // 62
    "Func1_2149AA4",  // 63
    "Func1_2149AB0",  // 64
    "Func1_2149ABC",  // 65
    "Func1_2149AC8",  // 66
    "Func1_2149AD8",  // 67
    "Func1_2149B98",  // 68
    "Func1_2149BA8",  // 69
    "Func1_2149BC0",  // 70
    "Func1_2149BD8",  // 71
    "Func1_2149BF0",  // 72
    "Func1_2149C08",  // 73
    "Func1_2149C20",  // 74
    "Func1_2149C38",  // 75
    "Func1_2149C50",  // 76
    "Func1_2149C68",  // 77
    "Func1_2149C80",  // 78
    "Func1_2149C98",  // 79
    "Func1_2149D3C",  // 80
    "Func1_214A098",  // 81
    "Func1_214A39C",  // 82
    "Func1_SetInvulnerable",  // 83
    "Func1_UnlockEchoHallForceField",  // 84
};

inline constexpr std::uint8_t funcs1_table[] = {
    82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67,
    66, 65, 64, 63, 62, 61, 60, 59, 57, 55, 53, 51, 49, 47, 58, 56,
    54, 52, 50, 48, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35,
    34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19,
    18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3,
    2, 1, 84, 83,
};

// ExecuteFuncs2: 126 identifiers, 16 distinct behaviours.
inline constexpr const char* funcs2_names[] = {
    "",  // 0: runs nothing
    "Func2_213D96C",  // 1
    "Func2_213D9B8",  // 2
    "Func2_213DA88",  // 3
    "Func2_213DDCC",  // 4
    "Func2_213E148",  // 5
    "Func2_213E1CC",  // 6
    "Func2_213E274",  // 7
    "Func2_213E31C",  // 8
    "Func2_213E3C4",  // 9
    "Func2_213E684",  // 10
    "Func2_213E904",  // 11
    "Func2_213E934",  // 12
    "Func2_213E984",  // 13
    "Func2_213E9C8",  // 14
    "Func2_213EA10",  // 15
    "Func2_213EA48",  // 16
};

inline constexpr std::uint8_t funcs2_table[] = {
    0, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 4, 16, 3,
    16, 5, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 14,
    13, 12, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 11, 10, 16, 9, 16, 8, 7, 16, 16, 16, 16, 16, 16,
    16, 16, 6, 16, 16, 16, 16, 16, 16, 16, 16, 2, 1, 0,
};

// ExecuteFuncs4: 126 identifiers, 13 distinct behaviours.
inline constexpr const char* funcs4_names[] = {
    "",  // 0: runs nothing
    "Func4_2145E40",  // 1
    "Func4_2145E54",  // 2
    "Func4_2145EB0",  // 3
    "Func4_2145F00",  // 4
    "Func4_2145F28",  // 5
    "Func4_2145F50",  // 6
    "Func4_2145F78",  // 7
    "Func4_214612C",  // 8
    "Func4_21461EC",  // 9
    "Func4_2146284",  // 10
    "Func4_21462AC",  // 11
    "Func4_21462DC",  // 12
    "Func4_SetDespawned",  // 13
};

inline constexpr std::uint8_t funcs4_table[] = {
    0, 0, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 3, 12, 0,
    12, 0, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 11,
    10, 9, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 0, 8, 12, 7, 12, 6, 5, 12, 12, 12, 12, 12, 12,
    12, 12, 4, 12, 12, 12, 12, 12, 12, 12, 12, 2, 1, 13,
};

} // namespace fruityprime::players::ai_dispatch
