// Generated by tools/gen-ai-methods.py from
// src/MphRead/Entities/Players/PlayerAi.cs.  Do not edit by hand.
//
// PlayerAi's Func2_* and Func4_* behaviours: what a bot does
// while it is in an execution node, and what it does on
// entering one.
#include "Entities/Players/PlayerAi.hpp"

#include "Utility/rng.hpp"

namespace fruityprime::players {
namespace {

template <typename Flags>
[[nodiscard]] constexpr Flags without(Flags value,
                                      Flags bit) noexcept {
    return static_cast<Flags>(
        static_cast<std::uint32_t>(value)
        & ~static_cast<std::uint32_t>(bit));
}

} // namespace

using utility::get_random_int2;

void PlayerAiData::func2_213D96C(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // CheckUnmorph();
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Debug.Assert(_targetPlayer != null);
    // Func2145C14(_targetPlayer.Position);
    // }
}

void PlayerAiData::func2_213D9B8(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (_player.IsAltForm)
    // {
    // CheckUnmorph();
    // }
    // else
    // {
    // Debug.Assert(_node40 != null);
    // Func2142ABC(_node40.Position);
    // Field118++;
    // if (!_player.Flags1.TestFlag(PlayerFlags1.UsedJump) && _buttons.L.FramesUp > 5 * 2
    // && (_player._standTerrain == Terrain.Lava
    // || _player._horizColTimer > 10 * 2 && _player.Flags1.TestFlag(PlayerFlags1.Grounded)))
    // {
    // _buttons.L.IsDown = true;
    // }
    // Func2140B18(context, _node40.Position);
    // }
}

void PlayerAiData::func2_213DA88(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (_player.IsAltForm)
    // {
    // _buttons.A.IsDown = true;
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Debug.Assert(_targetPlayer != null);
    // Vector3 zero = Vector3.Zero;
    // float targetLengthSqr = _targetPlayer.Position.WithY(0).LengthSquared;
    // float selfLengthSqr = _player.Position.WithY(0).LengthSquared;
    // bool spawnBomb = false;
    // if (_player.SyluxBombCount == 0)
    // {
    // spawnBomb = _buttons.L.FramesUp > 1 * 2;
    // }
    // else if (_player.SyluxBombCount == 1 || _player.SyluxBombCount == 2)
    // {
    // BombEntity? bomb = _player.SyluxBombs[_player.SyluxBombCount - 1];
    // Debug.Assert(bomb != null);
    // Vector3 bombPos = bomb.Position.WithY(0);
    // if (bombPos != Vector3.Zero)
    // {
    // bombPos = bombPos.Normalized();
    // }
    // else
    // {
    // bombPos = Vector3.UnitX;
    // }
    // Vector3 selfPos = _player.Position.WithY(0);
    // if (selfPos != Vector3.Zero)
    // {
    // selfPos = selfPos.Normalized();
    // }
    // else
    // {
    // selfPos = bombPos;
    // }
    // spawnBomb = Vector3.Dot(bombPos, selfPos) < -0.5f;
    // }
    // if (selfLengthSqr < targetLengthSqr + 2 * 2)
    // {
    // _buttons.B.IsDown = true;
    // }
    // else if (selfLengthSqr > targetLengthSqr + 3 * 3)
    // {
    // _buttons.X.IsDown = true;
    // }
    // Func2145C14(zero);
    // if (spawnBomb)
    // {
    // _buttons.L.IsDown = true;
    // }
    // }
    // }
    // else if (_touchButtons.Morph.FramesUp > 10 * 2)
    // {
    // _touchButtons.Morph.IsDown = true;
    // }
}

void PlayerAiData::func2_213DDCC(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (_player.IsAltForm)
    // {
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Func2142DCC();
    // Debug.Assert(_targetPlayer != null);
    // Func2145C14(_targetPlayer.Position);
    // bool spawnBomb = false;
    // if (_player.SyluxBombCount == 0)
    // {
    // spawnBomb = true;
    // if (Rng.GetRandomInt2(2) == 0)
    // {
    // Flags2 &= ~AiFlags2.Bit12;
    // }
    // else
    // {
    // Flags2 |= AiFlags2.Bit12;
    // }
    // }
    // else if (_player.SyluxBombCount == 1 || _player.SyluxBombCount == 2)
    // {
    // BombEntity? firstBomb = _player.SyluxBombs[_player.SyluxBombCount - 1];
    // Debug.Assert(firstBomb != null);
    // Vector3 targetToBomb = (firstBomb.Position - _targetPlayer.Position).WithY(0);
    // if (targetToBomb != Vector3.Zero)
    // {
    // targetToBomb = targetToBomb.Normalized();
    // }
    // else
    // {
    // targetToBomb = Vector3.UnitX;
    // }
    // Vector3 targetToSelf = (_player.Position - _targetPlayer.Position).WithY(0);
    // if (targetToSelf != Vector3.Zero)
    // {
    // targetToSelf = targetToSelf.Normalized();
    // }
    // else
    // {
    // targetToSelf = targetToBomb;
    // }
    // if (Vector3.Dot(targetToBomb, targetToSelf) < -0.5f)
    // {
    // if (_player.SyluxBombCount == 1)
    // {
    // spawnBomb = true;
    // }
    // else
    // {
    // Vector3 added = targetToBomb + targetToSelf;
    // if (added == Vector3.Zero)
    // {
    // spawnBomb = true;
    // }
    // else
    // {
    // BombEntity? secondBomb = _player.SyluxBombs[0];
    // Debug.Assert(secondBomb != null);
    // targetToBomb = (secondBomb.Position - _targetPlayer.Position).WithY(0);
    // spawnBomb = Vector3.Dot(added, targetToBomb) > 0;
    // }
    // }
    // }
    // }
    // if (Func2142EB0(context))
    // {
    // spawnBomb = true;
    // }
    // if (spawnBomb && _player._abilities.TestFlag(AbilityFlags.Bombs) && _player._bombAmmo > 0
    // && _player._bombCooldown == 0 && _buttons.L.FramesUp > _field102E)
    // {
    // _buttons.L.IsDown = true;
    // _field102E = _field102C + Rng.GetRandomInt2(_field102C / 2);
    // }
    // }
    // }
    // else if (_touchButtons.Morph.FramesUp > 10 * 2)
    // {
    // _touchButtons.Morph.IsDown = true;
    // }
}

void PlayerAiData::func2_213E148(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (!_player.IsAltForm && _touchButtons.Morph.FramesUp > 10 * 2)
    // {
    // _touchButtons.Morph.IsDown = true;
    // }
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Func2142FC0();
    // Debug.Assert(_targetPlayer != null);
    // Func2145C14(_targetPlayer.Position);
    // }
}

void PlayerAiData::func2_213E1CC(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // CheckUnmorph();
    // if (Flags2.TestFlag(AiFlags2.TargetHalfturret))
    // {
    // Func2143470();
    // Func21430B4();
    // }
    // if (!_player.Flags1.TestFlag(PlayerFlags1.UsedJump) && _buttons.L.FramesUp > _field1034)
    // {
    // _buttons.L.IsDown = true;
    // _field1034 = Rng.GetRandomInt2(75 * 2) + 15 * 2;
    // }
}

void PlayerAiData::func2_213E274(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // CheckUnmorph();
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Func21436D8();
    // Func21431B4();
    // }
    // if (!_player.Flags1.TestFlag(PlayerFlags1.UsedJump) && _buttons.L.FramesUp > _field1034)
    // {
    // _buttons.L.IsDown = true;
    // _field1034 = Rng.GetRandomInt2(75 * 2) + 15 * 2;
    // }
}

void PlayerAiData::func2_213E31C(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // CheckUnmorph();
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Func21433E4();
    // }
    // Func2142D38();
    // if (!_player.Flags1.TestFlag(PlayerFlags1.UsedJump) && _buttons.L.FramesUp > _field1034)
    // {
    // _buttons.L.IsDown = true;
    // _field1034 = Rng.GetRandomInt2(75 * 2) + 15 * 2;
    // }
}

void PlayerAiData::func2_213E3C4(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (_player.IsAltForm)
    // {
    // CheckUnmorph();
    // }
    // else if (Flags2.TestFlag(AiFlags2.TargetDefense))
    // {
    // Debug.Assert(_targetDefense != null);
    // float radius = 0;
    // if (_targetDefense.Volume.Type == VolumeType.Cylinder)
    // {
    // radius = _targetDefense.Volume.CylinderRadius;
    // }
    // else if (_targetDefense.Volume.Type == VolumeType.Sphere)
    // {
    // radius = _targetDefense.Volume.SphereRadius;
    // }
    // if (radius > 0.5f)
    // {
    // Vector3 toDefense = (_targetDefense.Position - _player.Position).WithY(0);
    // if (radius * radius <= toDefense.LengthSquared)
    // {
    // Field118 = 0;
    // context.Field40 = 0;
    // context.Field44 = 0;
    // context.Field34 = _player.Position;
    // _field78 = 0;
    // Flags2 &= ~AiFlags2.Bit15;
    // float x = Rng.GetRandomInt2(4096) / 4096f;
    // _fieldA0 = new Vector3(x * MathF.Sign(toDefense.X), 0, MathF.Sqrt(1 - x * x) * MathF.Sign(toDefense.Z));
    // _fieldA0 *= radius;
    // _fieldA0 += _targetDefense.Position;
    // }
    // Func2142AE8(_fieldA0);
    // Field118++;
    // Func2140B18(context, _fieldA0);
    // }
    // Func21436D8();
    // }
    // if (Flags2.TestFlag(AiFlags2.Bit10) && Rng.GetRandomInt2(10) == 0 && !_player.IsAltForm && !_player.IsMorphing
    // && !_player.Flags1.TestFlag(PlayerFlags1.UsedJump) && _buttons.L.FramesUp > 5 * 2)
    // {
    // _buttons.L.IsDown = true;
    // }
}

void PlayerAiData::func2_213E684(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (_player.IsAltForm)
    // {
    // float distSqr = 7 * 7;
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Debug.Assert(_targetPlayer != null);
    // distSqr = Vector3.DistanceSquared(_targetPlayer.Position, _player.Position);
    // }
    // context.Field2C = 0;
    // if (_player.SyluxBombCount != 1 && (distSqr >= 10 * 10 || _player.SyluxBombCount != 0))
    // {
    // Func2140094(context);
    // }
    // if (_player._abilities.TestFlag(AbilityFlags.Bombs) && _player._bombAmmo > 0
    // && _player._bombCooldown == 0 && _buttons.L.FramesUp > 1 * 2)
    // {
    // if (distSqr >= 10 * 10 || _player.SyluxBombCount != 0)
    // {
    // if (_player.SyluxBombCount == 1)
    // {
    // _buttons.A.IsDown = false;
    // _buttons.Y.IsDown = true;
    // _buttons.X.IsDown = false;
    // _buttons.B.IsDown = false;
    // if (_buttons.Y.FramesDown > 10 * 2 && _buttons.L.FramesUp != 0)
    // {
    // _buttons.L.IsDown = true;
    // }
    // }
    // else if (_player.SyluxBombCount == 2 && _buttons.L.FramesUp > 150 * 2)
    // {
    // _buttons.L.IsDown = true;
    // }
    // }
    // else
    // {
    // _buttons.A.IsDown = true;
    // _buttons.Y.IsDown = false;
    // _buttons.X.IsDown = false;
    // _buttons.B.IsDown = false;
    // if (_buttons.A.FramesDown > 10 * 2 && _buttons.L.FramesUp != 0)
    // {
    // _buttons.L.IsDown = true;
    // }
    // }
    // }
    // }
    // else if (_touchButtons.Morph.FramesUp > 10 * 2)
    // {
    // _touchButtons.Morph.IsDown = true;
    // }
}

void PlayerAiData::func2_213E904(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Func2143578();
    // }
}

void PlayerAiData::func2_213E934(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // Func2140094(context);
    // if (_player.IsAltForm && _buttons.L.FramesUp > _player.Values.BombRefillTime)
    // {
    // _buttons.L.IsDown = true;
    // }
}

void PlayerAiData::func2_213E984(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    checkUnmorph(session, bot_slot);
}

void PlayerAiData::func2_213E9C8(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // CheckUnmorph();
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Func21436D8();
    // }
    // Func213FD94();
}

void PlayerAiData::func2_213EA10(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    if (!((session.player(bot_slot).flags & net::PlayerState::FlagAltForm) != 0))
    {
        if (touch_buttons_[AiTouchButtonId::Morph].frames_up > 20)
        {
            touch_buttons_[AiTouchButtonId::Morph].is_down = true;
        }
    }
}

void PlayerAiData::func2_213EA48(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (context.FieldD == 28 && _player.IsAltForm && context.Field4 != 37)
    // {
    // CheckUnmorph();
    // if (context.Field4 == 33)
    // {
    // Field118++;
    // }
    // }
    // else if (context.FieldD == 29 && !_player.IsAltForm && context.Field4 != 37)
    // {
    // if (_touchButtons.Morph.FramesUp > 10 * 2)
    // {
    // _touchButtons.Morph.IsDown = true;
    // }
    // }
    // Vector3 targetPos = Vector3.Zero;
    // if (_player.IsAltForm || context.FieldA == 31)
    // {
    // if (_player.Values.AltFormStrafe != 0 && context.FieldA == 31)
    // {
    // if (context.FieldB == 4 && Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Debug.Assert(_targetPlayer != null);
    // _targetPlayer.GetPosition(out targetPos);
    // targetPos = targetPos.AddY(_targetPlayer.IsAltForm
    // ? Fixed.ToFloat(_targetPlayer.Values.AltColYPos)
    // : 0.5f);
    // Func2145C14(targetPos);
    // }
    // else if (context.FieldB == 5 && Flags2.TestFlag(AiFlags2.TargetHalfturret))
    // {
    // Debug.Assert(_targetHalfturret != null);
    // _targetHalfturret.GetPosition(out targetPos);
    // Func2145C14(targetPos);
    // }
    // }
    // }
    // else if (context.FieldA == 32)
    // {
    // if (context.FieldB == 4 && Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Debug.Assert(_targetPlayer != null);
    // _targetPlayer.GetPosition(out targetPos);
    // targetPos = targetPos.AddY(_targetPlayer.IsAltForm
    // ? Fixed.ToFloat(_targetPlayer.Values.AltColYPos)
    // : 0.5f);
    // _field1038 = targetPos - _player.CameraInfo.Position;
    // _field1038 = _field1038 != Vector3.Zero ? _field1038.Normalized() : _player.CameraInfo.Facing;
    // }
    // else if (context.FieldB == 5 && Flags2.TestFlag(AiFlags2.TargetHalfturret))
    // {
    // Debug.Assert(_targetHalfturret != null);
    // _targetHalfturret.GetPosition(out targetPos);
    // _field1038 = targetPos - _player.CameraInfo.Position;
    // _field1038 = _field1038 != Vector3.Zero ? _field1038.Normalized() : _player.CameraInfo.Facing;
    // }
    // else if (context.FieldB == 27)
    // {
    // _field1038 = _fieldB8 - _player.CameraInfo.Position;
    // _field1038 = _field1038 != Vector3.Zero ? _field1038.Normalized() : _player.CameraInfo.Facing;
    // }
    // Func21447E8();
    // }
    // else if (context.FieldC == 55)
    // {
    // Func21433A0(_fieldB8);
    // }
    // else if (context.FieldC == 56)
    // {
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Func21436D8();
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1))
    // {
    // Func214380C();
    // }
    // }
    // else if (context.FieldC == 57)
    // {
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Func2143658();
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1))
    // {
    // Func214380C();
    // }
    // }
    // else if (context.FieldC == 59)
    // {
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Func21433E4();
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1))
    // {
    // Func214380C();
    // }
    // }
    // else if (context.FieldC == 60)
    // {
    // if (Flags2.TestFlag(AiFlags2.TargetHalfturret))
    // {
    // Func2143470();
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1))
    // {
    // Func214380C();
    // }
    // }
    // else if (context.FieldC == 61)
    // {
    // Debug.Assert(_targetDoor != null);
    // _targetDoor.GetPosition(out targetPos);
    // Func21433A0(targetPos);
    // }
    // else
    // {
    // Func2145BA0();
    // }
    // if (context.Field4 == 37)
    // {
    // if (context.FieldD == 29)
    // {
    // Func2140094(context);
    // if (_player.Values.AltFormStrafe != 0 && _buttonAimX == 0 && _buttonAimY == 0)
    // {
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer) && context.Field9 == 4)
    // {
    // Debug.Assert(_targetPlayer != null);
    // _targetPlayer.GetPosition(out targetPos);
    // targetPos = targetPos.AddY(_targetPlayer.IsAltForm
    // ? Fixed.ToFloat(_targetPlayer.Values.AltColYPos)
    // : 0.5f);
    // Func2145C14(targetPos);
    // }
    // else
    // {
    // Debug.Assert(_node40 != null);
    // Func2145C14(_node40.Position);
    // }
    // }
    // }
    // else if (context.Field5 != 58 || _player.IsAltForm)
    // {
    // Func2140094(context);
    // }
    // else
    // {
    // Func214003C(context);
    // }
    // if (context.Field6 == 52 && !_player.IsAltForm && !_player.IsMorphing
    // && !_player.Flags1.TestFlag(PlayerFlags1.UsedJump) && _buttons.L.FramesUp > 5 * 2)
    // {
    // AiPlayerAggro? aggro = AggroFunc214847C(4, 7, 1, null, null);
    // if (aggro != null && aggro.Staleness < 30 * 2)
    // {
    // Debug.Assert(_node40 != null);
    // Vector3 toNode = _node40.Position - _player.Position;
    // if (toNode.LengthSquared > 3 * 3)
    // {
    // _buttons.L.IsDown = true;
    // }
    // }
    // }
    // }
    // else if (context.Field4 == 33
    // && (context.Field9 != 4 || Flags2.TestFlag(AiFlags2.TargetPlayer))
    // && (context.Field9 != 5 || Flags2.TestFlag(AiFlags2.TargetHalfturret)))
    // {
    // Vector3? position = null;
    // if (context.Field9 == 4)
    // {
    // Debug.Assert(_targetPlayer != null);
    // position = _targetPlayer.Position;
    // }
    // else if (context.Field9 == 5)
    // {
    // Debug.Assert(_targetHalfturret != null);
    // position = _targetHalfturret.Position;
    // }
    // else if (context.Field9 == 6 && Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // Debug.Assert(_itemC8 != null);
    // position = targetPos = _itemC8.Position.AddY(-0.5f);
    // }
    // else if (context.Field9 == 12 || context.Field9 == 13 || context.Field9 == 39)
    // {
    // Debug.Assert(_node40 != null);
    // position = _node40.Position;
    // }
    // else if (context.Field9 == 14)
    // {
    // Debug.Assert(_octolithFlagCC != null);
    // position = _octolithFlagCC.Position;
    // }
    // else if (context.Field9 == 15)
    // {
    // Debug.Assert(_octolithFlagCC != null);
    // position = _octolithFlagCC.BasePosition;
    // }
    // else if (context.Field9 == 16)
    // {
    // Debug.Assert(_flagBaseD0 != null);
    // position = _flagBaseD0.Position;
    // }
    // else if (context.Field9 == 17)
    // {
    // Debug.Assert(_octolithFlagD4 != null);
    // position = _octolithFlagD4.Position;
    // }
    // else if (context.Field9 == 18)
    // {
    // Debug.Assert(_octolithFlagD4 != null);
    // position = _octolithFlagD4.BasePosition;
    // }
    // else if (context.Field9 == 19)
    // {
    // Debug.Assert(_flagBaseD8 != null);
    // position = _flagBaseD8.Position;
    // }
    // else if (context.Field9 == 20)
    // {
    // Debug.Assert(_octolithFlagDC != null);
    // position = _octolithFlagDC.Position;
    // }
    // else if (context.Field9 == 21)
    // {
    // Debug.Assert(_octolithFlagDC != null);
    // position = _octolithFlagDC.BasePosition;
    // }
    // else if (context.Field9 == 22)
    // {
    // Debug.Assert(_flagBaseE0 != null);
    // position = _flagBaseE0.Position;
    // }
    // else if (context.Field9 == 23 && Flags2.TestFlag(AiFlags2.TargetDefense))
    // {
    // Debug.Assert(_targetDefense != null);
    // position = _targetDefense.Position;
    // }
    // else if (context.Field9 == 35)
    // {
    // position = targetPos = _player.Position.AddZ(1);
    // }
    // else if (context.Field9 == 36)
    // {
    // position = targetPos = _player.Position.AddZ(-1);
    // }
    // if (position.HasValue)
    // {
    // if (_player.IsAltForm)
    // {
    // if (_player.Values.AltFormStrafe != 0)
    // {
    // Func2145C14(targetPos);
    // Func2142AE8(position.Value);
    // }
    // else if (context.Field5 != 48 || _player.Hunter != Hunter.Samus)
    // {
    // Func21418D8(position.Value);
    // }
    // else
    // {
    // Func2141840(position.Value);
    // }
    // }
    // else
    // {
    // Func2140B18(context, position.Value);
    // if (context.FieldA != 0 || context.FieldC == 56 || context.FieldC == 57 || context.FieldC == 59
    // || context.FieldC == 60 || context.FieldC == 61 || context.FieldC == 55)
    // {
    // Func2142AE8(position.Value);
    // }
    // else
    // {
    // Func2142ABC(position.Value);
    // }
    // if (!_player.IsMorphing && !_player.IsUnmorphing)
    // {
    // if (_player._horizColTimer > 10 * 2 && _player.Flags1.TestFlag(PlayerFlags1.Grounded))
    // {
    // PressL();
    // }
    // if (context.Field9 == 6 || context.Field9 == 14 || context.Field9 == 17 || context.Field9 == 20)
    // {
    // Vector3 toPos = position.Value - _player.Position;
    // toPos = toPos.AddY(-Fixed.ToFloat(_player.Values.MaxPickupHeight));
    // if (context.Field9 != 6)
    // {
    // toPos = toPos.AddY(-1.25f);
    // }
    // if (toPos.Y > -0.5f && toPos.WithY(0).LengthSquared < 0.5f * 0.5f)
    // {
    // PressL();
    // }
    // }
    // }
    // }
    // }
    // }
    // else if (context.Field4 == 34 && context.FieldD == 29)
    // {
    // if (!_player.IsAltForm)
    // {
    // PressButton(_touchButtons.Morph, 10);
    // }
    // else if (_fieldAC.X != 0 || _fieldAC.Z != 0)
    // {
    // Func2141CD4(_fieldAC);
    // }
    // }
    // if (context.FieldE == 38 && !_player.IsAltForm)
    // {
    // Func214380C();
    // }
    // if (context.FieldC == 62 && _player.IsAltForm)
    // {
    // void ShootAndSetDelay()
    // {
    // if (_buttons.L.FramesUp > _field102E)
    // {
    // _buttons.L.IsDown = true;
    // _field102E = _field102C + Rng.GetRandomInt2(_field102C / 2);
    // }
    // }
    // if (context.FieldF == 64)
    // {
    // if (_player._abilities.TestFlag(AbilityFlags.Bombs) && _player._bombAmmo > 0 && _player._bombCooldown == 0)
    // {
    // ShootAndSetDelay();
    // }
    // }
    // else if (context.FieldF == 65)
    // {
    // if (_player._abilities.TestFlag(AbilityFlags.Bombs) && _player._bombCooldown == 0)
    // {
    // ShootAndSetDelay();
    // }
    // }
    // else if (context.FieldF == 66)
    // {
    // if (_player._abilities.TestFlag(AbilityFlags.SpireAltAttack)
    // && !_player.Flags2.TestFlag(PlayerFlags2.AltAttack))
    // {
    // ShootAndSetDelay();
    // }
    // }
    // else if (context.FieldF == 67)
    // {
    // if (_player._altAttackTime > 0 || _buttons.L.FramesUp > _field102E)
    // {
    // _buttons.L.IsDown = true;
    // _field102E = _field102C + Rng.GetRandomInt2(_field102C / 2);
    // }
    // }
    // else if (context.FieldF == 68)
    // {
    // if (_player._abilities.TestFlag(AbilityFlags.TraceAltAttack)
    // && _player._altAttackCooldown == 0 && Flags2.TestFlag(AiFlags2.Bit0))
    // {
    // ShootAndSetDelay();
    // }
    // }
    // else if (context.FieldF == 69)
    // {
    // if (Rng.GetRandomInt2(15 * _player.SyluxBombCount + 10) == 0
    // && _player._abilities.TestFlag(AbilityFlags.Bombs)
    // && _player._bombAmmo > 0 && _player._bombCooldown == 0)
    // {
    // ShootAndSetDelay();
    // }
    // }
    // else if (context.FieldF == 70)
    // {
    // if (_player._abilities.TestFlag(AbilityFlags.WeavelAltAttack)
    // && _player._altAttackCooldown == 0 && Flags2.TestFlag(AiFlags2.Bit0))
    // {
    // ShootAndSetDelay();
    // }
    // }
    // }
    // else if (context.FieldC == 63)
    // {
    // if (context.FieldF == 65)
    // {
    // if (_player._abilities.TestFlag(AbilityFlags.Bombs)
    // && _player._bombCooldown == 0 && _buttons.L.FramesUp > 60 * 2)
    // {
    // _buttons.L.IsDown = true;
    // }
    // }
    // else if (context.FieldF == 69 && _player.SyluxBombCount < 2)
    // {
    // Debug.Assert(_node3C != null);
    // if (IsNodeInRange(_node3C) && _player._abilities.TestFlag(AbilityFlags.Bombs)
    // && _player._bombAmmo > 0 && _player._bombCooldown == 0 && _buttons.L.FramesUp > 0)
    // {
    // _buttons.L.IsDown = true;
    // }
    // }
    // }
    // if (!_player.IsAltForm && !_player.IsMorphing && Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Debug.Assert(_targetPlayer != null);
    // if (_targetPlayer.Hunter == Hunter.Sylux && _targetPlayer.IsAltForm && Func2139C60(_targetPlayer))
    // {
    // PressL();
    // }
    // }
    // if (context.Field6 == 51 && !_player.IsAltForm && !_player.IsMorphing
    // && !_player.Flags1.TestFlag(PlayerFlags1.UsedJump))
    // {
    // PressButton(_buttons.L, 5);
    // }
    // if (Flags2.TestFlag(AiFlags2.Bit21) && Rng.GetRandomInt2(10) == 0
    // && !_player.IsAltForm && !_player.IsMorphing && !_player.Flags1.TestFlag(PlayerFlags1.UsedJump))
    // {
    // PressButton(_buttons.L, 5);
    // }
    // if (context.Func24Id == 95
    // && !_player.IsAltForm && !_player.IsMorphing && !_player.Flags1.TestFlag(PlayerFlags1.UsedJump)
    // && Metadata.SlipSpeedFactors[_player._slipperiness] > 0 && _player._hSpeedMag > 0)
    // {
    // PressButton(_buttons.L, 5);
    // }
}

void PlayerAiData::func4_2145E40(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    flags3_ = flags3_ | AiFlags3::Bit1;
}

void PlayerAiData::func4_2145E54(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    find_entity_ref(AiEntRefType::Type0);
    node40_ = entity_refs_.entity(0);
    node3c_ = node40_;
    field118_ = 0;
    context.field40 = 0;
    context.field44 = 0;
    context.field34 = session.player(bot_slot).position;
}

void PlayerAiData::func4_2145EB0(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    context.field40 = 0;
    context.field34 = session.player(bot_slot).position;
    if (utility::get_random_int2(2u) == 0u)
    {
        flags2_ = without(flags2_, AiFlags2::Bit12);
    }
    else
    {
        flags2_ = flags2_ | AiFlags2::Bit12;
    }
}

void PlayerAiData::func4_2145F00(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    func4_21462AC(session, bot_slot, context);
}

void PlayerAiData::func4_2145F28(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    func4_21462AC(session, bot_slot, context);
}

void PlayerAiData::func4_2145F50(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    func4_21462AC(session, bot_slot, context);
}

void PlayerAiData::func4_2145F78(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (!Flags2.TestFlag(AiFlags2.TargetDefense))
    // {
    // Func2135320();
    // }
    // Field118 = 0;
    // _field78 = 0;
    // Flags2 &= ~AiFlags2.Bit15;
    // context.Field40 = 0;
    // context.Field44 = 0;
    // context.Field34 = _player.Position;
    // if (Flags2.TestFlag(AiFlags2.TargetDefense))
    // {
    // Debug.Assert(_targetDefense != null);
    // float radius = 0;
    // if (_targetDefense.Volume.Type == VolumeType.Cylinder)
    // {
    // radius = _targetDefense.Volume.CylinderRadius;
    // }
    // else if (_targetDefense.Volume.Type == VolumeType.Sphere)
    // {
    // radius = _targetDefense.Volume.SphereRadius;
    // }
    // if (radius > 0.5f)
    // {
    // Vector3 toDefense = (_targetDefense.Position - _player.Position).WithY(0);
    // float x = Rng.GetRandomInt2(4096) / 4096f;
    // _fieldA0 = new Vector3(x * MathF.Sign(toDefense.X), 0, MathF.Sqrt(1 - x * x) * MathF.Sign(toDefense.Z));
    // _fieldA0 *= radius;
    // _fieldA0 += _targetDefense.Position;
    // }
    // }
}

void PlayerAiData::func4_214612C(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // Field118 = 0;
    // _field78 = 0;
    // Flags2 &= ~AiFlags2.Bit15;
    // context.Field40 = 0;
    // context.Field44 = 0;
    // context.Field34 = _player.Position;
    // context.Field20 = 0;
    // context.Field24 = 1;
    // context.Field14 = 0;
    // context.Field18 = 0;
    // context.Field1C = 0;
    // context.Field2C = 0;
    // context.Field28 = true;
    // context.Field30 = true;
    // FindEntityRef(AiEntRefType.Type1);
    // _node40 = _entityRefs.Field1;
    // FindEntityRef(AiEntRefType.Type25);
    // _node3C = _entityRefs.Field25;
    // _queuedFindEntityAction = AiQueuedEnt.None;
    // Debug.Assert(_node40 != null);
    // if (IsNodeInRange(_node40))
    // {
    // NodeData3 node = Func213A1A8();
    // _node44 = _node40;
    // _node40 = node;
    // }
}

void PlayerAiData::func4_21461EC(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    find_entity_ref(AiEntRefType::Type1);
    node40_ = entity_refs_.entity(1);
    if (has_flag(flags2_, AiFlags2::TargetPlayer))
    {
        find_entity_ref(AiEntRefType::Type17);
        node3c_ = entity_refs_.entity(17);
    }
    else
    {
        node3c_ = node40_;
    }
    field118_ = 0;
    field78_ = 0;
    flags2_ = without(flags2_, AiFlags2::Bit15);
    queued_find_entity_action_ = AiQueuedEnt::Type3;
    context.field20 = 0;
    context.field24 = 1;
    context.field14 = 0;
    context.field18 = 0;
    context.field1c = 0;
    context.field2c = 0;
    context.field28 = true;
    context.field30 = false;
}

void PlayerAiData::func4_2146284(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    func4_21462AC(session, bot_slot, context);
}

void PlayerAiData::func4_21462AC(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    if (((session.player(bot_slot).flags & net::PlayerState::FlagAltForm) != 0))
    {
        touch_buttons_[AiTouchButtonId::Unmorph].is_down = true;
    }
}

void PlayerAiData::func4_21462DC(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // Func214715C(context);
    // if (context.FieldA == 31)
    // {
    // Flags2 &= ~AiFlags2.Bit0;
    // }
    // Vector3 targetPos = Vector3.Zero;
    // Vector3 halfturretPos = Vector3.Zero;
    // if (context.Field9 == 4 || context.FieldB == 4 || context.Field9 == 41 || context.FieldC == 56
    // || context.FieldC == 57 || context.FieldC == 59 || context.Field5 == 58)
    // {
    // if (context.Field7 == 1)
    // {
    // Func2135510();
    // }
    // if (context.Field7 == 2)
    // {
    // Func21354B0();
    // }
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer) && _targetPlayer != null)
    // {
    // _targetPlayer.GetPosition(out targetPos);
    // targetPos = targetPos
    // .AddY(_targetPlayer.IsAltForm ? Fixed.ToFloat(_targetPlayer.Values.AltColYPos) : 0.5f);
    // }
    // }
    // if (Flags2.TestFlag(AiFlags2.TargetHalfturret) && _targetHalfturret != null
    // && (context.Field9 == 5 || context.FieldB == 5 || context.FieldC == 60))
    // {
    // _targetHalfturret.GetPosition(out halfturretPos);
    // }
    // if (context.Field9 == 6)
    // {
    // if (context.Field8 == 7)
    // {
    // FindEntityRef(AiEntRefType.Type55);
    // UpdateTargetItem(_entityRefs.Field55);
    // }
    // else if (context.Field8 == 8)
    // {
    // FindEntityRef(AiEntRefType.Type56);
    // UpdateTargetItem(_entityRefs.Field56);
    // }
    // else if (context.Field8 == 9)
    // {
    // FindEntityRef(AiEntRefType.Type57);
    // UpdateTargetItem(_entityRefs.Field57);
    // }
    // else if (context.Field8 == 10)
    // {
    // FindEntityRef(AiEntRefType.Type58);
    // UpdateTargetItem(_entityRefs.Field58);
    // }
    // else if (context.Field8 == 11)
    // {
    // FindEntityRef(AiEntRefType.Type59);
    // UpdateTargetItem(_entityRefs.Field59);
    // }
    // }
    // if (context.Field9 == 23 && !Flags2.TestFlag(AiFlags2.TargetDefense))
    // {
    // Func2135320();
    // }
    // if (context.FieldC == 61 && !Flags2.TestFlag(AiFlags2.TargetDoor))
    // {
    // Func21355D8();
    // }
    // if (context.FieldA == 32)
    // {
    // if (context.FieldB == 4 && Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // _field1038 = targetPos - _player.CameraInfo.Position;
    // }
    // else if (context.FieldB == 3 && Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // AiPlayerAggro? aggro = AggroFunc214847C(4, 7, 1, null, null);
    // if (aggro?.Player1 != null)
    // {
    // _field1038 = aggro.Player1.Position - _player.CameraInfo.Position;
    // }
    // else
    // {
    // _field1038 = _player.CameraInfo.Facing;
    // }
    // }
    // else if (context.FieldB == 5 && Flags2.TestFlag(AiFlags2.TargetHalfturret))
    // {
    // _field1038 = halfturretPos - _player.CameraInfo.Position;
    // }
    // else if (context.FieldB == 25)
    // {
    // float x = Rng.GetRandomInt2(4096) / 4096f - 0.5f;
    // float y = Rng.GetRandomInt2(4096) / 4096f - 0.5f;
    // float z = Rng.GetRandomInt2(4096) / 4096f - 0.5f;
    // _field1038 = new Vector3(x, y, z);
    // }
    // else if (context.FieldB == 26)
    // {
    // float x = Rng.GetRandomInt2(4096) / 4096f - 0.5f;
    // float z = Rng.GetRandomInt2(4096) / 4096f - 0.5f;
    // float length = MathF.Sqrt(x * x + z * z);
    // float y = Rng.GetRandomInt2(Fixed.ToInt(length)) / 4096f - length / 2;
    // _field1038 = new Vector3(x, y, z);
    // }
    // else if (context.FieldB == 27)
    // {
    // _field1038 = _fieldB8 - _player.CameraInfo.Position;
    // }
    // if (_field1038 != Vector3.Zero)
    // {
    // _field1038 = _field1038.Normalized();
    // }
    // else
    // {
    // _field1038 = _player.CameraInfo.Facing;
    // }
    // }
    // if (context.Field4 != 0)
    // {
    // Field118 = 0;
    // _field78 = 0;
    // Flags2 &= ~AiFlags2.Bit15;
    // context.Field40 = 0;
    // context.Field44 = 0;
    // context.Field34 = _player.Position;
    // }
    // NodeData3? v25 = null;
    // if (context.Field4 == 37 || context.Field9 == 39)
    // {
    // bool node40Set = false;
    // if (Flags2.TestFlag(AiFlags2.Bit7) && context.Field4 == 37)
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node40 = _entityRefs.Field0;
    // if (_node40 == _node48)
    // {
    // v25 = Func213A1A8();
    // if (v25 == _field4C[0])
    // {
    // _node44 = _node40;
    // _node40 = v25;
    // node40Set = true;
    // }
    // }
    // else if (!_player.Flags1.TestFlag(PlayerFlags1.Grounded))
    // {
    // _node40 = _field4C[0];
    // node40Set = true;
    // }
    // }
    // if (!node40Set)
    // {
    // FindEntityRef(AiEntRefType.Type1);
    // _node40 = _entityRefs.Field1;
    // }
    // Debug.Assert(_node40 != null);
    // if (_node40.NodeType != NodeType.AltForm || _player.Hunter == Hunter.Guardian)
    // {
    // context.Field18 = 1;
    // }
    // else
    // {
    // context.Field18 = 2;
    // }
    // }
    // if (context.Field4 == 33)
    // {
    // if (context.Field9 == 12)
    // {
    // FindEntityRef(AiEntRefType.Type25);
    // _node3C = _node40 = _entityRefs.Field25;
    // }
    // else if (context.Field9 == 13)
    // {
    // FindEntityRef(AiEntRefType.Type24);
    // _node3C = _node40 = _entityRefs.Field24;
    // }
    // else if (context.Field9 == 39)
    // {
    // _node3C = _node40;
    // }
    // else if (context.Field9 != 4)
    // {
    // Vector3? position = null;
    // if (context.Field9 == 5)
    // {
    // Debug.Assert(_targetHalfturret != null);
    // position = _targetHalfturret.Position;
    // }
    // else if (context.Field9 == 6)
    // {
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // Debug.Assert(_itemC8 != null);
    // position = _itemC8.Position.AddY(-0.5f);
    // }
    // }
    // else if (context.Field9 == 14)
    // {
    // Debug.Assert(_octolithFlagCC != null);
    // position = _octolithFlagCC.Position;
    // }
    // else if (context.Field9 == 15)
    // {
    // Debug.Assert(_octolithFlagCC != null);
    // position = _octolithFlagCC.BasePosition;
    // }
    // else if (context.Field9 == 16)
    // {
    // Debug.Assert(_flagBaseD0 != null);
    // position = _flagBaseD0.Position;
    // }
    // else if (context.Field9 == 17)
    // {
    // Debug.Assert(_octolithFlagD4 != null);
    // position = _octolithFlagD4.Position;
    // }
    // else if (context.Field9 == 18)
    // {
    // Debug.Assert(_octolithFlagD4 != null);
    // position = _octolithFlagD4.BasePosition;
    // }
    // else if (context.Field9 == 19)
    // {
    // Debug.Assert(_flagBaseD8 != null);
    // position = _flagBaseD8.Position;
    // }
    // else if (context.Field9 == 20)
    // {
    // Debug.Assert(_octolithFlagDC != null);
    // position = _octolithFlagDC.Position;
    // }
    // else if (context.Field9 == 21)
    // {
    // Debug.Assert(_octolithFlagDC != null);
    // position = _octolithFlagDC.BasePosition;
    // }
    // else if (context.Field9 == 22)
    // {
    // Debug.Assert(_flagBaseE0 != null);
    // position = _flagBaseE0.Position;
    // }
    // else if (context.Field9 == 23 && Flags2.TestFlag(AiFlags2.TargetDefense))
    // {
    // Debug.Assert(_targetDefense != null);
    // position = _targetDefense.Position;
    // }
    // if (position.HasValue)
    // {
    // NodeData3 node = FindClosestNonHazardNodeToPosition(position.Value);
    // if (node.NodeType == NodeType.AltForm && _player.Hunter != Hunter.Guardian
    // && context.FieldD != 29)
    // {
    // context.FieldD = 29;
    // context.FieldE = 0;
    // }
    // }
    // }
    // }
    // else if (context.Field4 == 34)
    // {
    // if (context.Field9 == 4 && Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Debug.Assert(_targetPlayer != null);
    // _fieldAC = (_targetPlayer.Position - _player.Position).WithY(0);
    // }
    // else if (context.Field9 == 5 && Flags2.TestFlag(AiFlags2.TargetHalfturret))
    // {
    // Debug.Assert(_targetHalfturret != null);
    // _fieldAC = (_targetHalfturret.Position - _player.Position).WithY(0);
    // }
    // if (_fieldAC.X != 0 || _fieldAC.Z != 0)
    // {
    // _fieldAC = _fieldAC.Normalized();
    // }
    // }
    // else if (context.Field4 == 37)
    // {
    // context.Field20 = 0;
    // context.Field24 = 1;
    // context.Field14 = 0;
    // context.Field18 = 0;
    // context.Field1C = 0;
    // if (context.Field5 == 47)
    // {
    // context.Field2C = 1;
    // }
    // else if (context.Field5 == 48)
    // {
    // context.Field2C = 2;
    // }
    // else
    // {
    // context.Field2C = 0;
    // }
    // context.Field28 = context.FieldD == 29;
    // context.Field30 = context.FieldA == 0
    // && context.FieldC != 55 && context.FieldC != 56 && context.FieldC != 57
    // && context.FieldC != 59 && context.FieldC != 60 && context.FieldC != 61;
    // if (context.Field9 == 4 && Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // FindEntityRef(AiEntRefType.Type2);
    // _node3C = _entityRefs.Field2;
    // _queuedFindEntityAction = AiQueuedEnt.Type0;
    // }
    // else if (context.Field9 == 5 && Flags2.TestFlag(AiFlags2.TargetHalfturret))
    // {
    // FindEntityRef(AiEntRefType.Type3);
    // _node3C = _entityRefs.Field3;
    // _queuedFindEntityAction = AiQueuedEnt.Type8;
    // }
    // else if (context.Field9 == 6 && Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // _queuedFindEntityAction = context.Field8 switch
    // {
    // 7 => AiQueuedEnt.Type12,
    // 8 => AiQueuedEnt.Type13,
    // 9 => AiQueuedEnt.Type14,
    // 10 => AiQueuedEnt.Type15,
    // 11 => AiQueuedEnt.Type16,
    // _ => AiQueuedEnt.None
    // };
    // }
    // else if (context.Field9 == 12)
    // {
    // FindEntityRef(AiEntRefType.Type25);
    // _node3C = _entityRefs.Field25;
    // _queuedFindEntityAction = AiQueuedEnt.None;
    // }
    // else if (context.Field9 == 13)
    // {
    // FindEntityRef(AiEntRefType.Type24);
    // _node3C = _entityRefs.Field24;
    // _queuedFindEntityAction = AiQueuedEnt.None;
    // }
    // else if (context.Field9 == 14)
    // {
    // FindEntityRef(AiEntRefType.Type6);
    // _node3C = _entityRefs.Field6;
    // _queuedFindEntityAction = AiQueuedEnt.Type27;
    // }
    // else if (context.Field9 == 15)
    // {
    // FindEntityRef(AiEntRefType.Type7);
    // _node3C = _entityRefs.Field7;
    // _queuedFindEntityAction = AiQueuedEnt.Type28;
    // }
    // else if (context.Field9 == 16)
    // {
    // FindEntityRef(AiEntRefType.Type8);
    // _node3C = _entityRefs.Field8;
    // _queuedFindEntityAction = AiQueuedEnt.Type29;
    // }
    // else if (context.Field9 == 17)
    // {
    // FindEntityRef(AiEntRefType.Type9);
    // _node3C = _entityRefs.Field9;
    // _queuedFindEntityAction = AiQueuedEnt.Type30;
    // }
    // else if (context.Field9 == 18)
    // {
    // FindEntityRef(AiEntRefType.Type10);
    // _node3C = _entityRefs.Field10;
    // _queuedFindEntityAction = AiQueuedEnt.Type31;
    // }
    // else if (context.Field9 == 19)
    // {
    // FindEntityRef(AiEntRefType.Type11);
    // _node3C = _entityRefs.Field11;
    // _queuedFindEntityAction = AiQueuedEnt.Type32;
    // }
    // else if (context.Field9 == 20)
    // {
    // FindEntityRef(AiEntRefType.Type12);
    // _node3C = _entityRefs.Field12;
    // _queuedFindEntityAction = AiQueuedEnt.Type33;
    // }
    // else if (context.Field9 == 21)
    // {
    // FindEntityRef(AiEntRefType.Type13);
    // _node3C = _entityRefs.Field13;
    // _queuedFindEntityAction = AiQueuedEnt.Type34;
    // }
    // else if (context.Field9 == 22)
    // {
    // FindEntityRef(AiEntRefType.Type14);
    // _node3C = _entityRefs.Field14;
    // _queuedFindEntityAction = AiQueuedEnt.Type35;
    // }
    // else if (context.Field9 == 23)
    // {
    // FindEntityRef(AiEntRefType.Type15);
    // _node3C = _entityRefs.Field15;
    // _queuedFindEntityAction = AiQueuedEnt.Type36;
    // }
    // else if (context.Field9 == 24)
    // {
    // _node3C = GetRandomNavigationNode();
    // _queuedFindEntityAction = AiQueuedEnt.None;
    // }
    // else if (context.Field9 == 40)
    // {
    // _node3C = FindHighestNode();
    // _queuedFindEntityAction = AiQueuedEnt.Type9;
    // }
    // else if (context.Field9 == 41 && Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // FindEntityRef(AiEntRefType.Type17);
    // _node3C = _entityRefs.Field17;
    // _queuedFindEntityAction = AiQueuedEnt.Type3;
    // }
    // else if (context.Field9 == 42 && Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // FindEntityRef(AiEntRefType.Type18);
    // _node3C = _entityRefs.Field18;
    // _queuedFindEntityAction = AiQueuedEnt.Type4;
    // }
    // else if (context.Field9 == 44)
    // {
    // FindEntityRef(AiEntRefType.Type23);
    // _node3C = _entityRefs.Field23;
    // _queuedFindEntityAction = AiQueuedEnt.None;
    // }
    // else if (context.Field9 == 45)
    // {
    // FindEntityRef(AiEntRefType.Type22);
    // _node3C = _entityRefs.Field22;
    // _queuedFindEntityAction = AiQueuedEnt.None;
    // }
    // else if (context.Field9 == 46)
    // {
    // FindEntityRef(AiEntRefType.Type21);
    // _node3C = _entityRefs.Field21;
    // _queuedFindEntityAction = AiQueuedEnt.None;
    // }
    // else
    // {
    // if (Flags2.TestFlag(AiFlags2.Bit1))
    // {
    // FindQueuedEntityRef();
    // }
    // else
    // {
    // _node3C = _node40;
    // }
    // _queuedFindEntityAction = AiQueuedEnt.None;
    // }
    // if (_node40 != null && IsNodeInRange(_node40))
    // {
    // if (v25 == null)
    // {
    // v25 = Func213A1A8();
    // }
    // bool v33 = false;
    // for (int i = 0; i < _node40.Count2; i++)
    // {
    // if (_node40.Values[_node40.Index2 + i] == v25.Id)
    // {
    // v33 = true;
    // break;
    // }
    // }
    // if (!v33)
    // {
    // _node48 = _node44 = _node40;
    // _field4C[0] = _node40 = v25;
    // if (_node40.NodeType != NodeType.AltForm || _player.Hunter == Hunter.Guardian)
    // {
    // context.Field18 = 1;
    // }
    // else
    // {
    // context.Field18 = 2;
    // }
    // Flags2 |= AiFlags2.Bit7;
    // }
    // }
    // }
    // if (context.Field5 == 47)
    // {
    // _field90 = _player.Position;
    // _field9C = 0.5f;
    // }
    // if (context.Field6 == 51 && !_player.IsAltForm && !_player.IsMorphing
    // && !_player.Flags1.TestFlag(PlayerFlags1.UsedJump) && _buttons.L.FramesUp > 5 * 2)
    // {
    // _buttons.L.IsDown = true;
    // }
}

void PlayerAiData::func4_SetDespawned(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    flags3_ = flags3_ | AiFlags3::Despawned;
}

// Behaviour index to behaviour, numbered the way
// tools/gen-ai-dispatch.py numbers them.
void PlayerAiData::dispatch_funcs2(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context,
    std::uint8_t behavior) noexcept {
    switch (behavior) {
    case 1:
        func2_213D96C(session, bot_slot, context);
        break;
    case 2:
        func2_213D9B8(session, bot_slot, context);
        break;
    case 3:
        func2_213DA88(session, bot_slot, context);
        break;
    case 4:
        func2_213DDCC(session, bot_slot, context);
        break;
    case 5:
        func2_213E148(session, bot_slot, context);
        break;
    case 6:
        func2_213E1CC(session, bot_slot, context);
        break;
    case 7:
        func2_213E274(session, bot_slot, context);
        break;
    case 8:
        func2_213E31C(session, bot_slot, context);
        break;
    case 9:
        func2_213E3C4(session, bot_slot, context);
        break;
    case 10:
        func2_213E684(session, bot_slot, context);
        break;
    case 11:
        func2_213E904(session, bot_slot, context);
        break;
    case 12:
        func2_213E934(session, bot_slot, context);
        break;
    case 13:
        func2_213E984(session, bot_slot, context);
        break;
    case 14:
        func2_213E9C8(session, bot_slot, context);
        break;
    case 15:
        func2_213EA10(session, bot_slot, context);
        break;
    case 16:
        func2_213EA48(session, bot_slot, context);
        break;
    default: break;  // 0 runs nothing
    }
}

// Behaviour index to behaviour, numbered the way
// tools/gen-ai-dispatch.py numbers them.
void PlayerAiData::dispatch_funcs4(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context,
    std::uint8_t behavior) noexcept {
    switch (behavior) {
    case 1:
        func4_2145E40(session, bot_slot, context);
        break;
    case 2:
        func4_2145E54(session, bot_slot, context);
        break;
    case 3:
        func4_2145EB0(session, bot_slot, context);
        break;
    case 4:
        func4_2145F00(session, bot_slot, context);
        break;
    case 5:
        func4_2145F28(session, bot_slot, context);
        break;
    case 6:
        func4_2145F50(session, bot_slot, context);
        break;
    case 7:
        func4_2145F78(session, bot_slot, context);
        break;
    case 8:
        func4_214612C(session, bot_slot, context);
        break;
    case 9:
        func4_21461EC(session, bot_slot, context);
        break;
    case 10:
        func4_2146284(session, bot_slot, context);
        break;
    case 11:
        func4_21462AC(session, bot_slot, context);
        break;
    case 12:
        func4_21462DC(session, bot_slot, context);
        break;
    case 13:
        func4_SetDespawned(session, bot_slot, context);
        break;
    default: break;  // 0 runs nothing
    }
}

} // namespace fruityprime::players
