// Generated by tools/gen-ai-funcs1.py from
// src/MphRead/Entities/Players/PlayerAi.cs.  Do not edit by hand.
//
// PlayerAi's Func1_* behaviours, which ExecuteFuncs1 dispatches to.
// A body the converter did not recognise says so where it stands,
// rather than compiling to a bot that quietly does nothing.
#include "Entities/Players/PlayerAi.hpp"

namespace fruityprime::players {
namespace {

template <typename Flags>
[[nodiscard]] constexpr Flags without(Flags value,
                                      Flags bit) noexcept {
    return static_cast<Flags>(
        static_cast<std::uint32_t>(value)
        & ~static_cast<std::uint32_t>(bit));
}

} // namespace

void PlayerAiData::func1_214A39C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    weapon1_ = 0;
    flags4_ = without(flags4_, AiFlags4::Bit1);
    if (check_beam(session, bot_slot, 6))
    {
        weapon1_ = 6;
    }
    else if (check_beam(session, bot_slot, 5))
    {
        weapon1_ = 5;
    }
    else if (check_beam(session, bot_slot, 4))
    {
        weapon1_ = 4;
    }
    else if (check_beam(session, bot_slot, 3))
    {
        weapon1_ = 3;
    }
    else if (check_beam(session, bot_slot, 2))
    {
        weapon1_ = 2;
    }
    else if (check_beam(session, bot_slot, 7))
    {
        weapon1_ = 7;
    }
    else if (check_beam(session, bot_slot, 1))
    {
        weapon1_ = 1;
    }
    if (check_charge(get_beam_type(static_cast<int>(weapon1_))))
    {
        flags4_ = flags4_ | AiFlags4::Bit1;
    }
}

void PlayerAiData::func1_214A098(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // BeamType affinityWeapon = Weapons.AffinityWeapons[(int)_player.Hunter];
    // int affinityIndex = GetWeaponIndex(affinityWeapon);
    // int seenBits = 1 | 2;
    // bool sawAffinity = false;
    // int seenCount = 0;
    // Span<int> seenItems = stackalloc int[7];
    // foreach (ItemSpawnEntity itemSpawn in _scene.GetItemSpawnEntities())
    // {
    // if (seenBits == 255)
    // {
    // break;
    // }
    // ItemType type = itemSpawn.Data.ItemType;
    // if (type == ItemType.AffinityWeapon)
    // {
    // type = (ItemType)affinityWeapon;
    // }
    // int index = type switch
    // {
    // ItemType.VoltDriver => 2,
    // ItemType.Battlehammer => 3,
    // ItemType.Imperialist => 4,
    // ItemType.Judicator => 5,
    // ItemType.Magmaul => 6,
    // ItemType.ShockCoil => 7,
    // ItemType.OmegaCannon => 8,
    // _ => 0
    // };
    // if ((seenBits & (1 << index)) == 0)
    // {
    // seenBits |= (1 << index);
    // if (!_player.AvailableWeapons[GetBeamType(index)])
    // {
    // seenItems[seenCount++] = index;
    // if (index == affinityIndex)
    // {
    // sawAffinity = true;
    // }
    // }
    // }
    // }
    // int randIdx = (int)Rng.GetRandomInt2(seenCount * (sawAffinity ? 2 : 1));
    // if (randIdx < seenCount)
    // {
    // _findWeaponIndex = seenItems[randIdx];
    // }
    // else
    // {
    // _findWeaponIndex = affinityIndex;
    // }
}

void PlayerAiData::func1_2149D3C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // if (CheckBeam(BeamType.OmegaCannon))
    // {
    // _weapon2 = 8;
    // return;
    // }
    // int affinityIndex = 0;
    // int candidateCount = 0;
    // Span<int> candidates = stackalloc int[8];
    // bool includeMissile = Weapons.AffinityWeapons[(int)_player.Hunter] == BeamType.Missile;
    // for (int i = includeMissile ? 1 : 2; i < 9; i++)
    // {
    // BeamType beam = GetBeamType(i);
    // if (CheckBeam(beam))
    // {
    // candidates[candidateCount++] = i;
    // if (Weapons.AffinityWeapons[(int)_player.Hunter] == beam)
    // {
    // affinityIndex = i;
    // }
    // }
    // }
    // if (candidateCount == 1)
    // {
    // candidates[0] = 1;
    // candidates[1] = 0;
    // candidateCount = 2;
    // }
    // else if (candidateCount == 0)
    // {
    // candidates[0] = 0;
    // candidateCount = 1;
    // if (CheckBeam(BeamType.Missile))
    // {
    // candidates[1] = 1;
    // candidateCount = 2;
    // }
    // }
    // int randIdx = (int)Rng.GetRandomInt2(candidateCount * (affinityIndex != 0 ? 2 : 1));
    // int noChargeChanceOneIn;
    // if (randIdx < candidateCount)
    // {
    // _weapon2 = candidates[randIdx];
    // noChargeChanceOneIn = 2;
    // }
    // else
    // {
    // _weapon2 = affinityIndex;
    // noChargeChanceOneIn = 4;
    // }
    // if (CheckCharge(GetBeamType(_weapon2)) && _player.BotLevel > 0)
    // {
    // if (Rng.GetRandomInt2(noChargeChanceOneIn) == 0)
    // {
    // Flags4 &= ~AiFlags4.Bit1;
    // }
    // else
    // {
    // Flags4 |= AiFlags4.Bit1;
    // }
    // }
}

void PlayerAiData::func1_2149C98(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // _weapon1 = CheckBeam(GetBeamType(_weapon2)) ? _weapon2 : 0;
}

void PlayerAiData::func1_2149C80(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    weapon1_ = 0;
    flags4_ = without(flags4_, AiFlags4::Bit1);
}

void PlayerAiData::func1_2149C68(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    weapon1_ = 2;
    flags4_ = without(flags4_, AiFlags4::Bit1);
}

void PlayerAiData::func1_2149C50(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    weapon1_ = 2;
    flags4_ = flags4_ | AiFlags4::Bit1;
}

void PlayerAiData::func1_2149C38(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    weapon1_ = 5;
    flags4_ = without(flags4_, AiFlags4::Bit1);
}

void PlayerAiData::func1_2149C20(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    weapon1_ = 5;
    flags4_ = flags4_ | AiFlags4::Bit1;
}

void PlayerAiData::func1_2149C08(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    weapon1_ = 4;
    flags4_ = without(flags4_, AiFlags4::Bit1);
}

void PlayerAiData::func1_2149BF0(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    weapon1_ = 6;
    flags4_ = without(flags4_, AiFlags4::Bit1);
}

void PlayerAiData::func1_2149BD8(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    weapon1_ = 6;
    flags4_ = flags4_ | AiFlags4::Bit1;
}

void PlayerAiData::func1_2149BC0(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    weapon1_ = 7;
    flags4_ = without(flags4_, AiFlags4::Bit1);
}

void PlayerAiData::func1_2149BA8(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    weapon1_ = 3;
    flags4_ = without(flags4_, AiFlags4::Bit1);
}

void PlayerAiData::func1_2149B98(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    flags4_ = flags4_ | AiFlags4::Bit1;
}

void PlayerAiData::func1_2149AD8(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // if (_buttons.R.FramesDown == 0 || _player.IsAltForm)
    // {
    // return;
    // }
    // if (CanChargeWeapon())
    // {
    // _buttons.R.IsDown = true;
    // }
}

void PlayerAiData::func1_2149AC8(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    flags4_ = flags4_ | AiFlags4::Bit2;
}

void PlayerAiData::func1_2149ABC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    octolith_flag_cc_ = octolith_flag_d4_;
}

void PlayerAiData::func1_2149AB0(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    octolith_flag_cc_ = octolith_flag_dc_;
}

void PlayerAiData::func1_2149AA4(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    flag_base_d0_ = flag_base_d8_;
}

void PlayerAiData::func1_2149A98(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    flag_base_d0_ = flag_base_e0_;
}

void PlayerAiData::func1_2149A64(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type54);
    update_target_item(session,
                       entity_refs_.entity(54));
}

void PlayerAiData::func1_2149824(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    if (find_weapon_index_ == 1)
    {
        if (session.inventory(bot_slot).available_weapons[1])
        {
            find_entity_ref(AiEntRefType::Type57);
            update_target_item(session,
                               entity_refs_.entity(57));
        }
        else
        {
            find_entity_ref(AiEntRefType::Type56);
            update_target_item(session,
                               entity_refs_.entity(56));
        }
    }
    else if (find_weapon_index_ == 2)
    {
        if (session.inventory(bot_slot).available_weapons[2])
        {
            find_entity_ref(AiEntRefType::Type59);
            update_target_item(session,
                               entity_refs_.entity(59));
        }
        else
        {
            find_entity_ref(AiEntRefType::Type58);
            update_target_item(session,
                               entity_refs_.entity(58));
        }
    }
    else if (find_weapon_index_ == 3)
    {
        if (session.inventory(bot_slot).available_weapons[3])
        {
            find_entity_ref(AiEntRefType::Type60);
            update_target_item(session,
                               entity_refs_.entity(60));
        }
        else
        {
            find_entity_ref(AiEntRefType::Type61);
            update_target_item(session,
                               entity_refs_.entity(61));
        }
    }
    else if (find_weapon_index_ == 4)
    {
        if (session.inventory(bot_slot).available_weapons[4])
        {
            find_entity_ref(AiEntRefType::Type63);
            update_target_item(session,
                               entity_refs_.entity(63));
        }
        else
        {
            find_entity_ref(AiEntRefType::Type62);
            update_target_item(session,
                               entity_refs_.entity(62));
        }
    }
    else if (find_weapon_index_ == 5)
    {
        if (session.inventory(bot_slot).available_weapons[5])
        {
            find_entity_ref(AiEntRefType::Type65);
            update_target_item(session,
                               entity_refs_.entity(65));
        }
        else
        {
            find_entity_ref(AiEntRefType::Type64);
            update_target_item(session,
                               entity_refs_.entity(64));
        }
    }
    else if (find_weapon_index_ == 6)
    {
        if (session.inventory(bot_slot).available_weapons[6])
        {
            find_entity_ref(AiEntRefType::Type67);
            update_target_item(session,
                               entity_refs_.entity(67));
        }
        else
        {
            find_entity_ref(AiEntRefType::Type66);
            update_target_item(session,
                               entity_refs_.entity(66));
        }
    }
    else if (find_weapon_index_ == 7)
    {
        if (session.inventory(bot_slot).available_weapons[7])
        {
            find_entity_ref(AiEntRefType::Type69);
            update_target_item(session,
                               entity_refs_.entity(69));
        }
        else
        {
            find_entity_ref(AiEntRefType::Type68);
            update_target_item(session,
                               entity_refs_.entity(68));
        }
    }
    else if (find_weapon_index_ == 8)
    {
        if (session.inventory(bot_slot).available_weapons[8])
        {
            find_entity_ref(AiEntRefType::Type71);
            update_target_item(session,
                               entity_refs_.entity(71));
        }
        else
        {
            find_entity_ref(AiEntRefType::Type70);
            update_target_item(session,
                               entity_refs_.entity(70));
        }
    }
    else
    {
        update_target_item(session, -1);
    }
}

void PlayerAiData::func1_21497F0(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type55);
    update_target_item(session,
                       entity_refs_.entity(55));
}

void PlayerAiData::func1_2149570(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type56);
    update_target_item(session,
                       entity_refs_.entity(56));
}

void PlayerAiData::func1_21494FC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type57);
    update_target_item(session,
                       entity_refs_.entity(57));
}

void PlayerAiData::func1_2149488(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type58);
    update_target_item(session,
                       entity_refs_.entity(58));
}

void PlayerAiData::func1_2149414(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type59);
    update_target_item(session,
                       entity_refs_.entity(59));
}

void PlayerAiData::func1_21493A0(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type72);
    update_target_item(session,
                       entity_refs_.entity(72));
}

void PlayerAiData::func1_214932C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type73);
    update_target_item(session,
                       entity_refs_.entity(73));
}

void PlayerAiData::func1_21495A4(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // void SetEntity(ItemSpawnEntity? entity)
    // {
    // _itemSpawnC4 = entity?.Item != null ? entity : null;
    // }
    // if (_findWeaponIndex == 1)
    // {
    // if (_player._availableWeapons[BeamType.Missile])
    // {
    // FindEntityRef(AiEntRefType.Type37);
    // SetEntity(_entityRefs.Field37);
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type36);
    // SetEntity(_entityRefs.Field36);
    // }
    // }
    // else if (_findWeaponIndex == 2)
    // {
    // if (_player._availableWeapons[BeamType.VoltDriver])
    // {
    // FindEntityRef(AiEntRefType.Type39);
    // SetEntity(_entityRefs.Field39);
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type38);
    // SetEntity(_entityRefs.Field38);
    // }
    // }
    // else if (_findWeaponIndex == 3)
    // {
    // if (_player._availableWeapons[BeamType.Battlehammer])
    // {
    // FindEntityRef(AiEntRefType.Type41);
    // SetEntity(_entityRefs.Field41);
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type40);
    // SetEntity(_entityRefs.Field40);
    // }
    // }
    // else if (_findWeaponIndex == 4)
    // {
    // if (_player._availableWeapons[BeamType.Imperialist])
    // {
    // FindEntityRef(AiEntRefType.Type43);
    // SetEntity(_entityRefs.Field43);
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type42);
    // SetEntity(_entityRefs.Field42);
    // }
    // }
    // else if (_findWeaponIndex == 5)
    // {
    // if (_player._availableWeapons[BeamType.Judicator])
    // {
    // FindEntityRef(AiEntRefType.Type45);
    // SetEntity(_entityRefs.Field45);
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type44);
    // SetEntity(_entityRefs.Field44);
    // }
    // }
    // else if (_findWeaponIndex == 6)
    // {
    // if (_player._availableWeapons[BeamType.Magmaul])
    // {
    // FindEntityRef(AiEntRefType.Type47);
    // SetEntity(_entityRefs.Field47);
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type46);
    // SetEntity(_entityRefs.Field46);
    // }
    // }
    // else if (_findWeaponIndex == 7)
    // {
    // if (_player._availableWeapons[BeamType.ShockCoil])
    // {
    // FindEntityRef(AiEntRefType.Type49);
    // SetEntity(_entityRefs.Field49);
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type48);
    // SetEntity(_entityRefs.Field48);
    // }
    // }
    // else if (_findWeaponIndex == 8)
    // {
    // if (_player._availableWeapons[BeamType.ShockCoil])
    // {
    // FindEntityRef(AiEntRefType.Type51);
    // SetEntity(_entityRefs.Field51);
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type50);
    // SetEntity(_entityRefs.Field50);
    // }
    // }
    // else
    // {
    // _itemSpawnC4 = null;
    // }
}

void PlayerAiData::func1_2149530(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type36);
    set_item_spawn(entity_refs_.entity(36));
}

void PlayerAiData::func1_21494BC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type37);
    set_item_spawn(entity_refs_.entity(37));
}

void PlayerAiData::func1_2149448(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type38);
    set_item_spawn(entity_refs_.entity(38));
}

void PlayerAiData::func1_21493D4(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type39);
    set_item_spawn(entity_refs_.entity(39));
}

void PlayerAiData::func1_2149360(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type52);
    set_item_spawn(entity_refs_.entity(52));
}

void PlayerAiData::func1_21492EC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    find_entity_ref(AiEntRefType::Type53);
    set_item_spawn(entity_refs_.entity(53));
}

void PlayerAiData::func1_21492DC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // if (PlayerEntity.Main == null)
    // {
    // Flags2 |= AiFlags2.Bit9;
    // }
    // else
    // {
    // Flags2 &= ~AiFlags2.Bit9;
    // Func21356C0(PlayerEntity.Main);
    // }
}

void PlayerAiData::func1_21492CC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // FindEntityRef(AiEntRefType.Type27);
    // Func21356C0(_entityRefs.Field27);
}

void PlayerAiData::func1_21492BC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // Func2135510();
}

void PlayerAiData::func1_21492AC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // Func21354E0();
}

void PlayerAiData::func1_214929C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // Func2135510();
}

void PlayerAiData::func1_214928C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // Func21354B0();
}

void PlayerAiData::func1_214927C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // Func2135380();
}

void PlayerAiData::func1_214926C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // Func2135480();
}

void PlayerAiData::func1_214925C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // if (GameState.PrimeHunter == -1 || _player.SlotIndex == GameState.PrimeHunter)
    // {
    // FindEntityRef(AiEntRefType.Type32);
    // Func21356C0(_entityRefs.Field32);
    // }
    // else
    // {
    // Flags2 &= ~AiFlags2.Bit9;
    // Func21356C0(PlayerEntity.Players[GameState.PrimeHunter]);
    // }
}

void PlayerAiData::func1_214924C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // Func21354B0();
}

void PlayerAiData::func1_214923C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // Debug.Assert(_octolithFlagCC != null);
    // if (_octolithFlagCC.Carrier != null && _octolithFlagCC.Carrier.Health != 0)
    // {
    // Func21356C0(_octolithFlagCC.Carrier);
    // Flags2 &= ~AiFlags2.Bit9;
    // }
    // else
    // {
    // Flags2 |= AiFlags2.Bit9;
    // }
}

void PlayerAiData::func1_214922C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // FindEntityRef(AiEntRefType.Type33);
    // if (_entityRefs.Field33 != null)
    // {
    // Flags2 |= AiFlags2.TargetHalfturret;
    // }
    // else
    // {
    // Flags2 &= ~AiFlags2.TargetHalfturret;
    // }
    // if (_entityRefs.Field33 != _targetHalfturret)
    // {
    // _targetHalfturret = _entityRefs.Field33;
    // _entityRefs.Field3 = null;
    // }
}

void PlayerAiData::func1_214921C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // FindEntityRef(AiEntRefType.Type75);
    // Func2135624(_entityRefs.Field75);
}

void PlayerAiData::func1_214920C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // FindEntityRef(AiEntRefType.Type76);
    // Func2135624(_entityRefs.Field76);
}

void PlayerAiData::func1_21491FC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // Func21355D8();
}

void PlayerAiData::func1_21491E4(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type0;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_21491CC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type1;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_21491B4(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type2;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_214919C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type3;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_2149184(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type5;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_214916C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type6;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_2149154(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type7;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_214913C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type9;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_2149124(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type10;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_214910C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type11;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_21490F4(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type12;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_21490DC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type13;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_21490C4(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type14;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_21490AC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type15;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_2149094(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    queued_find_entity_action_ = AiQueuedEnt::Type16;
    flags2_ = flags2_ | AiFlags2::Bit1;
}

void PlayerAiData::func1_2149088(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    field30_ = 1;
}

void PlayerAiData::func1_2149034(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // int navIndex = _nodeTypeIndex[(int)NodeType.Navigation];
    // int specIndex = _nodeTypeIndex[(int)NodeType.Special];
    // if (navIndex == specIndex)
    // {
    // _field30 = 0;
    // }
    // else
    // {
    // int offset = (int)Rng.GetRandomInt2((ushort)(specIndex - navIndex));
    // _field30 = (int)_nodeList[navIndex + offset].Field4;
    // }
}

void PlayerAiData::func1_2148F10(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // int navIndex = _nodeTypeIndex[(int)NodeType.Navigation];
    // int specIndex = _nodeTypeIndex[(int)NodeType.Special];
    // if (navIndex == specIndex)
    // {
    // _field30 = 0;
    // }
    // else
    // {
    // int i = 0;
    // int offsetCount = 0;
    // Span<int> offsets = stackalloc int[10];
    // while (offsetCount < 10 && i < specIndex - navIndex)
    // {
    // if (GameState.Mode == GameMode.Capture && _player.TeamIndex == 1)
    // {
    // uint field4 = _nodeList[navIndex + i].Field4;
    // if (field4 > 100 && field4 <= 110)
    // {
    // offsets[offsetCount++] = i;
    // }
    // }
    // else if (_nodeList[navIndex + i].Field4 <= 10)
    // {
    // offsets[offsetCount++] = i;
    // }
    // i++;
    // }
    // int offset = offsets[(int)Rng.GetRandomInt2(offsetCount)];
    // _field30 = (int)_nodeList[navIndex + offset].Field4;
    // }
}

void PlayerAiData::func1_2148EDC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // int navIndex = _nodeTypeIndex[(int)NodeType.Navigation];
    // int specIndex = _nodeTypeIndex[(int)NodeType.Special];
    // if (specIndex <= navIndex)
    // {
    // _field30 = 0;
    // }
    // else
    // {
    // _field30 = (int)_nodeList[specIndex - 1].Field4;
    // }
}

void PlayerAiData::func1_2148ECC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // _field30++;
}

void PlayerAiData::func1_2148EB8(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // if (_field30 != 0)
    // {
    // _field30--;
    // }
}

void PlayerAiData::func1_2148EA8(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // _field30 += 10;
}

void PlayerAiData::func1_2148E98(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    node_data_sel_on_ = 255;
}

void PlayerAiData::func1_2148E88(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    node_data_sel_off_ = 255;
}

void PlayerAiData::func1_2148E74(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    flags3_ = flags3_ | AiFlags3::Bit5;
}

void PlayerAiData::func1_2148E64(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    flags2_ = flags2_ | AiFlags2::Bit18;
}

void PlayerAiData::func1_2148E54(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    flags2_ = flags2_ | AiFlags2::Bit19;
}

void PlayerAiData::func1_2148DF8(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // float volume = _player._soundSource.Volume;
    // _player._soundSource.Volume = 1;
    // _player._soundSource.PlaySfx(SfxId.TRACE_WARNING_SCR, noUpdate: true);
    // _player._soundSource.Volume = volume;
}

void PlayerAiData::func1_2148DE8(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    flags2_ = flags2_ | AiFlags2::Bit20;
}

void PlayerAiData::func1_2148D50(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // foreach (CamSeqEntity camSeq in _scene.GetCamSeqEntities())
    // {
    // if (camSeq.Id == 56)
    // {
    // _scene.SendMessage(Message.Activate, _player, camSeq, 0, 0);
    // break;
    // }
    // }
}

void PlayerAiData::func1_UnlockEchoHallForceField(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The converter did not understand every line of this body, and a
    // half-converted behaviour would run the parts it did understand without
    // the parts it did not.  The managed source follows verbatim.
    // foreach (ForceFieldEntity forceField in _scene.GetForceFieldEntities())
    // {
    // if (forceField.Id == 19)
    // {
    // _scene.SendMessage(Message.Unlock, _player, forceField, 0, 0);
    // break;
    // }
    // }
}

void PlayerAiData::func1_SetInvulnerable(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    flags3_ = flags3_ | AiFlags3::Invulnerable;
}

// Behaviour index to behaviour, numbered the way
// tools/gen-ai-dispatch.py numbers them.
void PlayerAiData::dispatch_funcs1(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    std::uint8_t behavior) noexcept {
    switch (behavior) {
    case 1: func1_2148D50(session, bot_slot); break;
    case 2: func1_2148DE8(session, bot_slot); break;
    case 3: func1_2148DF8(session, bot_slot); break;
    case 4: func1_2148E54(session, bot_slot); break;
    case 5: func1_2148E64(session, bot_slot); break;
    case 6: func1_2148E74(session, bot_slot); break;
    case 7: func1_2148E88(session, bot_slot); break;
    case 8: func1_2148E98(session, bot_slot); break;
    case 9: func1_2148EA8(session, bot_slot); break;
    case 10: func1_2148EB8(session, bot_slot); break;
    case 11: func1_2148ECC(session, bot_slot); break;
    case 12: func1_2148EDC(session, bot_slot); break;
    case 13: func1_2148F10(session, bot_slot); break;
    case 14: func1_2149034(session, bot_slot); break;
    case 15: func1_2149088(session, bot_slot); break;
    case 16: func1_2149094(session, bot_slot); break;
    case 17: func1_21490AC(session, bot_slot); break;
    case 18: func1_21490C4(session, bot_slot); break;
    case 19: func1_21490DC(session, bot_slot); break;
    case 20: func1_21490F4(session, bot_slot); break;
    case 21: func1_214910C(session, bot_slot); break;
    case 22: func1_2149124(session, bot_slot); break;
    case 23: func1_214913C(session, bot_slot); break;
    case 24: func1_2149154(session, bot_slot); break;
    case 25: func1_214916C(session, bot_slot); break;
    case 26: func1_2149184(session, bot_slot); break;
    case 27: func1_214919C(session, bot_slot); break;
    case 28: func1_21491B4(session, bot_slot); break;
    case 29: func1_21491CC(session, bot_slot); break;
    case 30: func1_21491E4(session, bot_slot); break;
    case 31: func1_21491FC(session, bot_slot); break;
    case 32: func1_214920C(session, bot_slot); break;
    case 33: func1_214921C(session, bot_slot); break;
    case 34: func1_214922C(session, bot_slot); break;
    case 35: func1_214923C(session, bot_slot); break;
    case 36: func1_214924C(session, bot_slot); break;
    case 37: func1_214925C(session, bot_slot); break;
    case 38: func1_214926C(session, bot_slot); break;
    case 39: func1_214927C(session, bot_slot); break;
    case 40: func1_214928C(session, bot_slot); break;
    case 41: func1_214929C(session, bot_slot); break;
    case 42: func1_21492AC(session, bot_slot); break;
    case 43: func1_21492BC(session, bot_slot); break;
    case 44: func1_21492CC(session, bot_slot); break;
    case 45: func1_21492DC(session, bot_slot); break;
    case 46: func1_21492EC(session, bot_slot); break;
    case 47: func1_214932C(session, bot_slot); break;
    case 48: func1_2149360(session, bot_slot); break;
    case 49: func1_21493A0(session, bot_slot); break;
    case 50: func1_21493D4(session, bot_slot); break;
    case 51: func1_2149414(session, bot_slot); break;
    case 52: func1_2149448(session, bot_slot); break;
    case 53: func1_2149488(session, bot_slot); break;
    case 54: func1_21494BC(session, bot_slot); break;
    case 55: func1_21494FC(session, bot_slot); break;
    case 56: func1_2149530(session, bot_slot); break;
    case 57: func1_2149570(session, bot_slot); break;
    case 58: func1_21495A4(session, bot_slot); break;
    case 59: func1_21497F0(session, bot_slot); break;
    case 60: func1_2149824(session, bot_slot); break;
    case 61: func1_2149A64(session, bot_slot); break;
    case 62: func1_2149A98(session, bot_slot); break;
    case 63: func1_2149AA4(session, bot_slot); break;
    case 64: func1_2149AB0(session, bot_slot); break;
    case 65: func1_2149ABC(session, bot_slot); break;
    case 66: func1_2149AC8(session, bot_slot); break;
    case 67: func1_2149AD8(session, bot_slot); break;
    case 68: func1_2149B98(session, bot_slot); break;
    case 69: func1_2149BA8(session, bot_slot); break;
    case 70: func1_2149BC0(session, bot_slot); break;
    case 71: func1_2149BD8(session, bot_slot); break;
    case 72: func1_2149BF0(session, bot_slot); break;
    case 73: func1_2149C08(session, bot_slot); break;
    case 74: func1_2149C20(session, bot_slot); break;
    case 75: func1_2149C38(session, bot_slot); break;
    case 76: func1_2149C50(session, bot_slot); break;
    case 77: func1_2149C68(session, bot_slot); break;
    case 78: func1_2149C80(session, bot_slot); break;
    case 79: func1_2149C98(session, bot_slot); break;
    case 80: func1_2149D3C(session, bot_slot); break;
    case 81: func1_214A098(session, bot_slot); break;
    case 82: func1_214A39C(session, bot_slot); break;
    case 83: func1_SetInvulnerable(session, bot_slot); break;
    case 84: func1_UnlockEchoHallForceField(session, bot_slot); break;
    default: break;  // 0 runs nothing
    }
}

} // namespace fruityprime::players
