// Generated by tools/gen-ai-methods.py from
// src/MphRead/Entities/Players/PlayerAi.cs.  Do not edit by hand.
//
// The helpers PlayerAi's behaviours call.  These are not
// dispatched by identifier; they are reached only from the
// behaviours in the other two files.
#include "Entities/Players/PlayerAi.hpp"

#include "Utility/rng.hpp"

namespace fruityprime::players {
namespace {

template <typename Flags>
[[nodiscard]] constexpr Flags without(Flags value,
                                      Flags bit) noexcept {
    return static_cast<Flags>(
        static_cast<std::uint32_t>(value)
        & ~static_cast<std::uint32_t>(bit));
}


// A Data5 parameter is a fixed-point number wherever it is
// compared against a position.
[[nodiscard]] constexpr float param_float(
    std::int32_t value) noexcept {
    return static_cast<float>(value) / 4096.0F;
}

} // namespace

using utility::get_random_int2;

void PlayerAiData::checkUnmorph(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    if ((((session.player(bot_slot).flags & net::PlayerState::FlagAltForm) != 0)) && (touch_buttons_[AiTouchButtonId::Unmorph].frames_up > 20))
    {
        touch_buttons_[AiTouchButtonId::Unmorph].is_down = true;
    }
}

void PlayerAiData::findQueuedEntityRef(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (_queuedFindEntityAction == AiQueuedEnt.Type0)
    // {
    // if (!Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type2);
    // _node3C = _entityRefs.Field2;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type1)
    // {
    // Func2135510();
    // FindEntityRef(AiEntRefType.Type2);
    // _node3C = _entityRefs.Field2;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type2)
    // {
    // Func21354E0();
    // FindEntityRef(AiEntRefType.Type2);
    // _node3C = _entityRefs.Field2;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type3)
    // {
    // Func2135510();
    // FindEntityRef(AiEntRefType.Type17);
    // _node3C = _entityRefs.Field17;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type4)
    // {
    // if (!Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type18);
    // _node3C = _entityRefs.Field18;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type5)
    // {
    // Func21354B0();
    // FindEntityRef(AiEntRefType.Type2);
    // _node3C = _entityRefs.Field2;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type6)
    // {
    // Func2135380();
    // FindEntityRef(AiEntRefType.Type2);
    // _node3C = _entityRefs.Field2;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type7)
    // {
    // Func21354B0();
    // FindEntityRef(AiEntRefType.Type17);
    // _node3C = _entityRefs.Field17;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type8)
    // {
    // if (!Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type3);
    // _node3C = _entityRefs.Field3;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type9)
    // {
    // FindEntityRef(AiEntRefType.Type19);
    // _node3C = _entityRefs.Field19;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type10)
    // {
    // FindEntityRef(AiEntRefType.Type54);
    // UpdateTargetItem(_entityRefs.Field54);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type11)
    // {
    // FindEntityRef(AiEntRefType.Type34);
    // if (_itemSpawnC4 != _entityRefs.Field34)
    // {
    // _itemSpawnC4 = _entityRefs.Field34;
    // if (_itemSpawnC4?.Item != null)
    // {
    // FindEntityRef(AiEntRefType.Type4);
    // _node3C = _entityRefs.Field4;
    // }
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type12)
    // {
    // FindEntityRef(AiEntRefType.Type55);
    // UpdateTargetItem(_entityRefs.Field55);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type13)
    // {
    // FindEntityRef(AiEntRefType.Type56);
    // UpdateTargetItem(_entityRefs.Field56);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type14)
    // {
    // FindEntityRef(AiEntRefType.Type57);
    // UpdateTargetItem(_entityRefs.Field57);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type15)
    // {
    // FindEntityRef(AiEntRefType.Type58);
    // UpdateTargetItem(_entityRefs.Field58);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type16)
    // {
    // FindEntityRef(AiEntRefType.Type59);
    // UpdateTargetItem(_entityRefs.Field59);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type17)
    // {
    // FindEntityRef(AiEntRefType.Type60);
    // UpdateTargetItem(_entityRefs.Field60);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type18)
    // {
    // FindEntityRef(AiEntRefType.Type61);
    // UpdateTargetItem(_entityRefs.Field61);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type19)
    // {
    // FindEntityRef(AiEntRefType.Type42);
    // UpdateTargetItem(_entityRefs.Field42?.Item);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type20)
    // {
    // FindEntityRef(AiEntRefType.Type43);
    // UpdateTargetItem(_entityRefs.Field43?.Item);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type21)
    // {
    // FindEntityRef(AiEntRefType.Type44);
    // UpdateTargetItem(_entityRefs.Field44?.Item);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type22)
    // {
    // FindEntityRef(AiEntRefType.Type45);
    // UpdateTargetItem(_entityRefs.Field45?.Item);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type23)
    // {
    // FindEntityRef(AiEntRefType.Type46);
    // UpdateTargetItem(_entityRefs.Field46?.Item);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type24)
    // {
    // FindEntityRef(AiEntRefType.Type47);
    // UpdateTargetItem(_entityRefs.Field47?.Item);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type25)
    // {
    // FindEntityRef(AiEntRefType.Type48);
    // UpdateTargetItem(_entityRefs.Field48?.Item);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type26)
    // {
    // FindEntityRef(AiEntRefType.Type49);
    // UpdateTargetItem(_entityRefs.Field49?.Item);
    // if (Flags2.TestFlag(AiFlags2.TargetItem))
    // {
    // FindEntityRef(AiEntRefType.Type5);
    // _node3C = _entityRefs.Field5;
    // }
    // else
    // {
    // FindEntityRef(AiEntRefType.Type0);
    // _node3C = _entityRefs.Field0;
    // }
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type27 || _queuedFindEntityAction == AiQueuedEnt.Type28)
    // {
    // FindEntityRef(AiEntRefType.Type6);
    // _node3C = _entityRefs.Field6;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type29)
    // {
    // FindEntityRef(AiEntRefType.Type8);
    // _node3C = _entityRefs.Field8;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type30 || _queuedFindEntityAction == AiQueuedEnt.Type31)
    // {
    // FindEntityRef(AiEntRefType.Type9);
    // _node3C = _entityRefs.Field9;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type32)
    // {
    // FindEntityRef(AiEntRefType.Type11);
    // _node3C = _entityRefs.Field11;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type33 || _queuedFindEntityAction == AiQueuedEnt.Type34)
    // {
    // FindEntityRef(AiEntRefType.Type12);
    // _node3C = _entityRefs.Field12;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type35)
    // {
    // FindEntityRef(AiEntRefType.Type14);
    // _node3C = _entityRefs.Field14;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type36)
    // {
    // FindEntityRef(AiEntRefType.Type15);
    // _node3C = _entityRefs.Field15;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type37)
    // {
    // FindEntityRef(AiEntRefType.Type20);
    // _node3C = _entityRefs.Field20;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type38)
    // {
    // FindEntityRef(AiEntRefType.Type21);
    // _node3C = _entityRefs.Field21;
    // }
    // else if (_queuedFindEntityAction == AiQueuedEnt.Type39)
    // {
    // FindEntityRef(AiEntRefType.Type22);
    // _node3C = _entityRefs.Field22;
    // }
}

void PlayerAiData::func2135320(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // FindEntityRef(AiEntRefType.Type74);
    // Func2135624(_entityRefs.Field74);
}

void PlayerAiData::func2135380(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // FindEntityRef(AiEntRefType.Type31);
    // Func21356C0(_entityRefs.Field31);
}

void PlayerAiData::func2135480(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // FindEntityRef(AiEntRefType.Type32);
    // Func21356C0(_entityRefs.Field32);
}

void PlayerAiData::func21354B0(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // FindEntityRef(AiEntRefType.Type30);
    // Func21356C0(_entityRefs.Field30);
}

void PlayerAiData::func21354E0(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // FindEntityRef(AiEntRefType.Type28);
    // Func21356C0(_entityRefs.Field28);
}

void PlayerAiData::func2135510(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // FindEntityRef(AiEntRefType.Type26);
    // Func21356C0(_entityRefs.Field26);
}

void PlayerAiData::func21355D8(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // FindEntityRef(AiEntRefType.Type77);
    // Func2135608(_entityRefs.Field77);
}

void PlayerAiData::func213FD94(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Debug.Assert(_targetPlayer != null);
    // Vector3 toTarget = _targetPlayer.Position - _player.Position;
    // float minLengthSqr = toTarget.LengthSquared;
    // BeamProjectileEntity? closestBeam = null;
    // for (int i = 0; i < _targetPlayer.EquipInfo.Beams.Length; i++)
    // {
    // BeamProjectileEntity beam = _targetPlayer.EquipInfo.Beams[i];
    // if (beam.Lifespan > 0)
    // {
    // Vector3 toBeam = beam.Position - _player.Position;
    // float toBeamLenSq = toBeam.LengthSquared;
    // if (toBeamLenSq > 0)
    // {
    // toBeam = toBeam.Normalized();
    // }
    // else
    // {
    // toBeam = beam.Direction;
    // }
    // Vector3 beamVelocity = beam.Velocity;
    // if (beamVelocity != Vector3.Zero)
    // {
    // beamVelocity = beamVelocity.Normalized();
    // }
    // else
    // {
    // beamVelocity = toBeam;
    // }
    // if (Vector3.Dot(toBeam, beamVelocity) <= Fixed.ToFloat(-2896) && toBeamLenSq <= minLengthSqr)
    // {
    // minLengthSqr = toBeamLenSq;
    // closestBeam = beam;
    // }
    // }
    // }
    // if (closestBeam != null)
    // {
    // Vector3 beamVelocityH = closestBeam.Velocity.WithY(0);
    // Vector3 altVec = _player.IsAltForm
    // ? new Vector3(_player._field80, 0, _player._field84)
    // : new Vector3(_player._field70, 0, _player._field74);
    // Vector3 cross = Vector3.Cross(altVec, beamVelocityH);
    // if (cross.Y > 0)
    // {
    // _buttons.A.IsDown = true;
    // }
    // else
    // {
    // _buttons.Y.IsDown = true;
    // }
    // _buttons.L.IsDown = true;
    // }
    // }
}

void PlayerAiData::func214003C(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Func21436D8();
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1))
    // {
    // Func214380C();
    // }
    // Func2140094(context);
}

void PlayerAiData::func2140094(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // void SetField118()
    // {
    // if (_scene.RoomId == 106
    // && _player.Position.X > -2 && _player.Position.X < 2
    // && _player.Position.Z > -2 && _player.Position.Z < 2
    // && _player.Speed.Y > 0 && _player.Position.Y - _node40.Position.Y > 1)
    // {
    // Field118 = 151 * 2;
    // }
    // else
    // {
    // Field118++;
    // }
    // }
    // while (Func2140584(context))
    // {
    // }
    // Debug.Assert(_node40 != null);
    // context.Field18 = _node40.NodeType == NodeType.AltForm && _player.Hunter != Hunter.Guardian ? 2 : 0;
    // if (_player.IsAltForm)
    // {
    // if (_player._deathaltTimer == 0 && (context.Field1C == 1 || !context.Field28 && context.Field18 != 2))
    // {
    // CheckUnmorph();
    // }
    // if (context.Field20 != 0 && (context.Field1C != 1 || _player._deathaltTimer != 0))
    // {
    // if (_player.Values.AltFormStrafe != 0)
    // {
    // if (context.Field30 && context.Field2C == 0)
    // {
    // Func2142A80();
    // }
    // else if (!context.Field30 && context.Field2C == 0)
    // {
    // Func2142AE8(_node40.Position);
    // }
    // else if (context.Field30 && context.Field2C == 1)
    // {
    // Func2141EA8();
    // }
    // else if (!context.Field30 && context.Field2C == 1)
    // {
    // Func214201C();
    // }
    // }
    // else if (context.Field2C == 1)
    // {
    // Func2140D5C();
    // }
    // else if (context.Field2C != 2 || Field118 != 0)
    // {
    // Func21418D8(_node40.Position);
    // }
    // else
    // {
    // Func214182C();
    // }
    // SetField118();
    // }
    // }
    // else
    // {
    // if (context.Field1C != 1 && (context.Field28 || context.Field18 == 2))
    // {
    // PressButton(_touchButtons.Morph, 10);
    // }
    // if (context.Field20 == 2)
    // {
    // PressL();
    // }
    // if (context.Field20 != 0)
    // {
    // if (Flags2.TestFlag(AiFlags2.Bit21) || _player.Flags1.TestFlag(PlayerFlags1.Grounded)
    // || (_player.Position - _node40.Position).WithY(0).LengthSquared > _node40.MaxDistance * _node40.MaxDistance)
    // {
    // if (context.Field30 && (context.Field2C == 0 || context.Field2C == 2 || context.Field20 == 2))
    // {
    // Func2142A80();
    // }
    // else if (!context.Field30 && (context.Field2C == 0 || context.Field2C == 2 || context.Field20 == 2))
    // {
    // Func2142AE8(_node40.Position);
    // }
    // else if (context.Field30 && context.Field2C == 1)
    // {
    // Func2141EA8();
    // }
    // else if (!context.Field30 && context.Field2C == 1)
    // {
    // Func214201C();
    // }
    // }
    // SetField118();
    // Func2140B18(context, _node40.Position);
    // }
    // }
}

void PlayerAiData::func2140D5C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (CheckSpireClimbInput())
    // {
    // return;
    // }
    // var altVec = new Vector3(_player._altRollFbX, 0, _player._altRollFbZ);
    // Helper02(altVec, _buttons.Up, _buttons.Down, _buttons.Left, _buttons.Right);
}

void PlayerAiData::func214182C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // Debug.Assert(_node40 != null);
    // Func2141840(_node40.Position);
}

void PlayerAiData::func2141EA8(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // Debug.Assert(_node40 != null);
    // Vector3 altVec = _player.IsAltForm
    // ? new Vector3(_player._field80, 0, _player._field84)
    // : new Vector3(_player._field70, 0, _player._field74);
    // Vector3 toNode = _node40.Position - (_node44?.Position ?? _field90);
    // toNode = toNode.X != 0 || toNode.Z != 0 ? toNode.WithY(0).Normalized() : altVec;
    // float dot = Vector3.Dot(altVec, toNode);
    // if (dot < 1)
    // {
    // if (dot > _dotValues[_player.BotLevel])
    // {
    // _buttonAimX = MathHelper.RadiansToDegrees(MathF.Acos(dot));
    // }
    // else
    // {
    // _buttonAimX = _aimValues[_player.BotLevel];
    // }
    // if (Vector3.Cross(altVec, toNode).Y < 0)
    // {
    // _buttonAimX *= -1;
    // }
    // }
    // Func214201C();
}

void PlayerAiData::func214201C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // Vector3 altVec = _player.IsAltForm
    // ? new Vector3(_player._field80, 0, _player._field84)
    // : new Vector3(_player._field70, 0, _player._field74);
    // Helper02(altVec, _buttons.X, _buttons.B, _buttons.Y, _buttons.A);
}

void PlayerAiData::func2142A80(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // Debug.Assert(_node40 != null);
    // Func2142AE8(_node40.Position);
    // Func2145C14(_node40.Position);
}

void PlayerAiData::func2142D38(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (_buttons.Y.FramesUp > 30 * 2 || _buttons.Y.FramesDown < 30 * 2 && _buttons.Y.FramesDown != 0)
    // {
    // _buttons.Y.IsDown = true;
    // }
    // else
    // {
    // _buttons.A.IsDown = true;
    // }
    // if (_buttons.X.FramesUp > 15 * 2 || _buttons.X.FramesDown < 15 * 2 && _buttons.X.FramesDown != 0)
    // {
    // _buttons.X.IsDown = true;
    // }
    // else
    // {
    // _buttons.B.IsDown = true;
    // }
}

void PlayerAiData::func2142DCC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (Flags2.TestFlag(AiFlags2.Bit12))
    // {
    // _buttons.A.IsDown = true;
    // }
    // else
    // {
    // _buttons.Y.IsDown = true;
    // }
    // Vector3 vec = ExecuteVectorFunc(index: 0, clearY: true, normalize: false);
    // float lengthSqr = vec.LengthSquared;
    // if (lengthSqr < 2 * 2)
    // {
    // _buttons.B.IsDown = true;
    // }
    // else if (lengthSqr > 3 * 3)
    // {
    // _buttons.X.IsDown = true;
    // }
}

void PlayerAiData::func2142FC0(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (_buttons.A.FramesDown < 180 * 2 && _buttons.Y.FramesUp != 0)
    // {
    // _buttons.A.IsDown = true;
    // }
    // else if (_buttons.Y.FramesDown < 180 * 2)
    // {
    // _buttons.Y.IsDown = true;
    // }
    // Vector3 vec = ExecuteVectorFunc(index: 0, clearY: true, normalize: false);
    // float lengthSqr = vec.LengthSquared;
    // if (lengthSqr < 2 * 2)
    // {
    // _buttons.B.IsDown = true;
    // }
    // else if (lengthSqr > 3 * 3)
    // {
    // _buttons.X.IsDown = true;
    // }
}

void PlayerAiData::func21430B4(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // Debug.Assert(_targetHalfturret != null);
    // if (_buttons.Y.FramesDown > 30 * 2 || _buttons.A.FramesDown < 60 * 2 && _buttons.A.FramesDown != 0)
    // {
    // _buttons.A.IsDown = true;
    // }
    // else
    // {
    // _buttons.Y.IsDown = true;
    // }
    // float distSqr = Vector3.DistanceSquared(_targetHalfturret.Position, _player.Position);
    // if (distSqr < 2 * 2)
    // {
    // _buttons.B.IsDown = true;
    // }
    // else if (distSqr > 3 * 3)
    // {
    // _buttons.X.IsDown = true;
    // }
}

void PlayerAiData::func21431B4(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // Debug.Assert(_targetPlayer != null);
    // Vector3 selfAltVec = _player.IsAltForm
    // ? new Vector3(_player._field80, 0, _player._field84)
    // : new Vector3(_player._field70, 0, _player._field74);
    // Vector3 targetAltVec = _targetPlayer.IsAltForm
    // ? new Vector3(_targetPlayer._field80, 0, _targetPlayer._field84)
    // : new Vector3(_targetPlayer._field70, 0, _targetPlayer._field74);
    // if (Vector3.Dot(selfAltVec, targetAltVec) <= Fixed.ToFloat(-3138))
    // {
    // if (_buttons.A.FramesDown != 0)
    // {
    // _buttons.A.IsDown = true;
    // }
    // else
    // {
    // _buttons.Y.IsDown = true;
    // }
    // }
    // else
    // {
    // Vector3 cross = Vector3.Cross(selfAltVec, targetAltVec);
    // if (cross.Y >= 0)
    // {
    // _buttons.A.IsDown = true;
    // }
    // else
    // {
    // _buttons.Y.IsDown = true;
    // }
    // }
    // Vector3 vec = ExecuteVectorFunc(index: 0, clearY: true, normalize: false);
    // float lengthSqr = vec.LengthSquared;
    // if (lengthSqr < 2 * 2)
    // {
    // _buttons.B.IsDown = true;
    // }
    // else if (lengthSqr > 3 * 3)
    // {
    // _buttons.X.IsDown = true;
    // }
}

void PlayerAiData::func21433E4(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Func2144B88();
    // Vector3 vec = ExecuteVectorFunc(index: 0, clearY: false, normalize: false);
    // if (Vector3.Dot(_player._facingVector, vec) > 0.866f)
    // {
    // Func2143A40();
    // }
    // }
}

void PlayerAiData::func2143470(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (Flags2.TestFlag(AiFlags2.TargetHalfturret))
    // {
    // Debug.Assert(_targetHalfturret != null);
    // Func2144964();
    // Vector3 toHalfturret = _targetHalfturret.Position - _player.Position;
    // if (Flags2.TestFlag(AiFlags2.Bit8) || toHalfturret.LengthSquared < 10)
    // {
    // Func2143A40();
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1) || _weapon1 == 0 || _weapon1 == 1)
    // {
    // Func214380C();
    // }
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1))
    // {
    // Func214380C();
    // }
}

void PlayerAiData::func2143578(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // Func21449DC();
    // _buttonAimX = Math.Clamp(_buttonAimX, -0.75f, 0.75f);
    // _buttonAimY = Math.Clamp(_buttonAimY, -0.75f, 0.75f);
    // if (_player.WeaponSelection != BeamType.Imperialist)
    // {
    // _touchButtons.Imperialist.IsDown = true;
    // }
    // else if (_buttons.R.FramesUp > 10 * 2)
    // {
    // _buttons.R.IsDown = true;
    // }
}

void PlayerAiData::func2143658(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Func2144AE4();
    // if (Flags2.TestFlag(AiFlags2.Bit8))
    // {
    // Func2143A40();
    // }
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1))
    // {
    // Func214380C();
    // }
}

void PlayerAiData::func21436D8(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Debug.Assert(_targetPlayer != null);
    // Func2144B88();
    // Vector3 vec = ExecuteVectorFunc(index: 0, clearY: false, normalize: false);
    // if (Flags2.TestFlag(AiFlags2.Bit8)
    // && Func213842C() && (IsPlayerVisible(_player, _targetPlayer) || _weapon1 == 7)
    // || vec.LengthSquared < 10)
    // {
    // Func2143A40();
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1) || _weapon1 <= 1)
    // {
    // Func214380C();
    // }
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1))
    // {
    // Func214380C();
    // }
}

void PlayerAiData::func214380C(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // EquipInfo equip = _player.EquipInfo;
    // WeaponInfo weapon = _player.EquipWeapon;
    // if (!weapon.Flags.TestFlag(WeaponFlags.CanCharge))
    // {
    // return;
    // }
    // BeamType beam = GetBeamType(_weapon1);
    // if (_player.CurrentWeapon != beam && _player._availableWeapons[beam])
    // {
    // if (beam == BeamType.PowerBeam)
    // {
    // _touchButtons.PowerBeam.IsDown = true;
    // }
    // else if (beam == BeamType.Missile)
    // {
    // _touchButtons.Missile.IsDown = true;
    // }
    // else if (beam == BeamType.VoltDriver)
    // {
    // _touchButtons.VoltDriver.IsDown = true;
    // }
    // else if (beam == BeamType.Judicator)
    // {
    // _touchButtons.Judicator.IsDown = true;
    // }
    // else if (beam == BeamType.Magmaul)
    // {
    // _touchButtons.Magmaul.IsDown = true;
    // }
    // return;
    // }
    // if (CanChargeWeapon() && (_buttons.R.FramesDown == 0 || equip.ChargeLevel > 0))
    // {
    // _buttons.R.IsDown = true;
    // }
}

void PlayerAiData::func2143A40(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // EquipInfo equip = _player.EquipInfo;
    // WeaponInfo weapon = _player.EquipWeapon;
    // int shotDelay;
    // if (_player.BotLevel == 0)
    // {
    // shotDelay = 60;
    // }
    // else if (_player.BotLevel == 1)
    // {
    // shotDelay = 15;
    // }
    // else
    // {
    // shotDelay = 5;
    // }
    // if (Flags2.TestFlag(AiFlags2.Bit21))
    // {
    // shotDelay /= 2;
    // }
    // shotDelay *= 2;
    // BeamType beam = GetBeamType(_weapon1);
    // if (beam != BeamType.ShockCoil && !_player.AvailableWeapons[beam])
    // {
    // return;
    // }
    // void SetRandomDelay()
    // {
    // _shotDelay = weapon.ShotCooldown * 2 + (int)Rng.GetRandomInt2(shotDelay);
    // }
    // if (beam == BeamType.PowerBeam)
    // {
    // if (_player.CurrentWeapon != beam)
    // {
    // _touchButtons.PowerBeam.IsDown = true;
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1) && CanChargeWeapon())
    // {
    // if (!_player.Flags2.TestFlag(PlayerFlags2.Shooting) && _buttons.R.FramesUp == 0
    // || equip.ChargeLevel >= weapon.FullCharge * 2)
    // {
    // SetRandomDelay();
    // }
    // else
    // {
    // _buttons.R.IsDown = true;
    // }
    // }
    // else if (_buttons.R.FramesDown > 0 && _buttons.R.FramesDown < _shotDelay)
    // {
    // _buttons.R.IsDown = true;
    // }
    // else if (_buttons.R.FramesUp <= _shotDelay)
    // {
    // SetRandomDelay();
    // }
    // else
    // {
    // _buttons.R.IsDown = true;
    // _shotDelay = (int)Rng.GetRandomInt2(weapon.FullCharge * 2);
    // }
    // }
    // else if (beam == BeamType.Missile)
    // {
    // if (_player.CurrentWeapon != beam)
    // {
    // _touchButtons.Missile.IsDown = true;
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1) && CanChargeWeapon())
    // {
    // if (!_player.Flags2.TestFlag(PlayerFlags2.Shooting) && _buttons.R.FramesUp <= _shotDelay
    // || equip.ChargeLevel >= weapon.FullCharge * 2)
    // {
    // SetRandomDelay();
    // }
    // else
    // {
    // _buttons.R.IsDown = true;
    // }
    // }
    // else if (_player.Flags1.TestFlag(PlayerFlags1.GunOpenAnimation) && _buttons.R.FramesUp > _shotDelay)
    // {
    // _buttons.R.IsDown = true;
    // SetRandomDelay();
    // }
    // }
    // else if (beam == BeamType.VoltDriver)
    // {
    // if (_player.CurrentWeapon != beam)
    // {
    // _touchButtons.VoltDriver.IsDown = true;
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1) && CanChargeWeapon())
    // {
    // if (!_player.Flags2.TestFlag(PlayerFlags2.Shooting) && _buttons.R.FramesUp <= _shotDelay
    // || equip.ChargeLevel >= weapon.FullCharge * 2)
    // {
    // SetRandomDelay();
    // }
    // else
    // {
    // _buttons.R.IsDown = true;
    // }
    // }
    // else if (_buttons.R.FramesUp > _shotDelay)
    // {
    // _buttons.R.IsDown = true;
    // SetRandomDelay();
    // }
    // }
    // else if (beam == BeamType.Battlehammer)
    // {
    // if (_player.CurrentWeapon != beam)
    // {
    // _touchButtons.Battlehammer.IsDown = true;
    // }
    // else if (_player.Flags1.TestFlag(PlayerFlags1.ShotUncharged) || _buttons.R.FramesUp > 0)
    // {
    // _buttons.R.IsDown = true;
    // }
    // }
    // else if (beam == BeamType.Imperialist)
    // {
    // if (_player.CurrentWeapon != beam)
    // {
    // _touchButtons.Imperialist.IsDown = true;
    // }
    // else if (_buttons.R.FramesUp > _shotDelay)
    // {
    // _buttons.R.IsDown = true;
    // }
    // }
    // else if (beam == BeamType.Judicator)
    // {
    // if (_player.CurrentWeapon != beam)
    // {
    // _touchButtons.Judicator.IsDown = true;
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1) && CanChargeWeapon())
    // {
    // if (!_player.Flags2.TestFlag(PlayerFlags2.Shooting) && _buttons.R.FramesUp <= _shotDelay
    // || equip.ChargeLevel >= weapon.FullCharge * 2)
    // {
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Debug.Assert(_targetPlayer != null);
    // Vector3 toTarget = _targetPlayer.Position - _player.Position;
    // float distSqr = toTarget.LengthSquared;
    // if (distSqr > 3 * 3 && _player.BotLevel == 0
    // || distSqr > 11 && _player.BotLevel == 1
    // || distSqr > 13)
    // {
    // SetRandomDelay();
    // }
    // else
    // {
    // _buttons.R.IsDown = true;
    // }
    // }
    // else
    // {
    // SetRandomDelay();
    // }
    // }
    // else
    // {
    // _buttons.R.IsDown = true;
    // }
    // }
    // else if (_buttons.R.FramesUp > _shotDelay)
    // {
    // _buttons.R.IsDown = true;
    // SetRandomDelay();
    // }
    // }
    // else if (beam == BeamType.Magmaul)
    // {
    // if (_player.CurrentWeapon != beam)
    // {
    // _touchButtons.Magmaul.IsDown = true;
    // }
    // else if (Flags4.TestFlag(AiFlags4.Bit1) && CanChargeWeapon())
    // {
    // if (!_player.Flags2.TestFlag(PlayerFlags2.Shooting) && _buttons.R.FramesUp <= _shotDelay
    // || equip.ChargeLevel >= weapon.FullCharge * 2)
    // {
    // SetRandomDelay();
    // }
    // else
    // {
    // _buttons.R.IsDown = true;
    // }
    // }
    // else if (_buttons.R.FramesUp > _shotDelay)
    // {
    // SetRandomDelay();
    // _buttons.R.IsDown = true;
    // }
    // }
    // else if (beam == BeamType.ShockCoil)
    // {
    // Debug.Assert(_targetPlayer != null);
    // Vector3 toTarget = _targetPlayer.Position - _player.Position;
    // float distSqr = toTarget.LengthSquared;
    // if (GameState.SinglePlayer || distSqr <= 15 * 15 || !_player.AvailableWeapons[BeamType.PowerBeam])
    // {
    // if (!_player.AvailableWeapons[beam])
    // {
    // return;
    // }
    // if (_player.CurrentWeapon != beam)
    // {
    // _touchButtons.ShockCoil.IsDown = true;
    // }
    // else if ((_player.Flags1.TestFlag(PlayerFlags1.ShotUncharged) || _buttons.R.FramesUp > 0)
    // && (distSqr < 15 * 15 || distSqr < 16 * 16 && _player.Flags1.TestFlag(PlayerFlags1.ShotUncharged)))
    // {
    // _buttons.R.IsDown = true;
    // }
    // }
    // else if (_player.CurrentWeapon != BeamType.PowerBeam)
    // {
    // _touchButtons.PowerBeam.IsDown = true;
    // }
    // else if (_buttons.R.FramesDown > 0 && _buttons.R.FramesDown < _shotDelay)
    // {
    // _buttons.R.IsDown = true;
    // }
    // else if (_buttons.R.FramesUp <= _shotDelay)
    // {
    // SetRandomDelay();
    // }
    // else
    // {
    // _buttons.R.IsDown = true;
    // _shotDelay = (int)Rng.GetRandomInt2(weapon.FullCharge * 2);
    // }
    // }
    // else if (beam == BeamType.OmegaCannon)
    // {
    // if (_player.CurrentWeapon != beam)
    // {
    // _touchButtons.OmegaCannon.IsDown = true;
    // }
    // else if (Flags2.TestFlag(AiFlags2.TargetPlayer) && _buttons.R.FramesUp > 0)
    // {
    // Debug.Assert(_targetPlayer != null);
    // Vector3 toTarget = _targetPlayer.Position - _player.Position;
    // if (toTarget.LengthSquared > 10 * 10)
    // {
    // _buttons.R.IsDown = true;
    // }
    // }
    // }
}

void PlayerAiData::func21447E8(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // var vec1 = new Vector3(_player.CameraInfo.Field48, 0, _player.CameraInfo.Field4C);
    // Vector3 vec2 = _field1038.X != 0 || _field1038.Z != 0 ? _field1038.WithY(0).Normalized() : vec1;
    // float dot = Vector3.Dot(vec1, vec2);
    // float value = _aimValues[_player.BotLevel];
    // if (dot < 1)
    // {
    // if (dot > _dotValues[_player.BotLevel])
    // {
    // _buttonAimX = MathHelper.RadiansToDegrees(MathF.Acos(dot));
    // }
    // else
    // {
    // _buttonAimX = value;
    // }
    // if (Vector3.Cross(vec1, vec2).Y < 0)
    // {
    // _buttonAimX *= -1;
    // }
    // }
    // float angle1 = 90 - MathHelper.RadiansToDegrees(MathF.Acos(_player.CameraInfo.Facing.Y));
    // float angle2 = 90 - MathHelper.RadiansToDegrees(MathF.Acos(_field1038.Y));
    // float angleDiff = angle2 - angle1;
    // _buttonAimY = Math.Clamp(angleDiff, -value, value);
}

void PlayerAiData::func2144964(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (Flags2.TestFlag(AiFlags2.TargetHalfturret))
    // {
    // Debug.Assert(_targetHalfturret != null);
    // _targetHalfturret.GetPosition(out Vector3 halfturretPos);
    // _field1048 = halfturretPos.AddY(0.5f);
    // Func2145738(_field1048);
    // }
}

void PlayerAiData::func21449DC(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // Debug.Assert(_targetPlayer != null);
    // _targetPlayer.GetPosition(out _field1048);
    // _field1048 = new Vector3(
    // _field1048.X + (Rng.GetRandomInt2(8192) / 4096f - 1),
    // _field1048.Y + (_targetPlayer.IsAltForm ? _targetPlayer.Values.AltColYPos : 0.5f),
    // _field1048.Z + (Rng.GetRandomInt2(8192) / 4096f - 1)
    // );
    // if (!Func213842C())
    // {
    // _field1048 = _field1048.AddZ(_field1048.Z < 0 ? -1.5f : 1.5f);
    // }
    // Func2145738(_field1048);
}

void PlayerAiData::func2144AE4(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // Debug.Assert(_targetPlayer != null);
    // _targetPlayer.GetPosition(out Vector3 targetPos);
    // _field1048 = targetPos.AddY(_targetPlayer.IsAltForm
    // ? Fixed.ToFloat(_targetPlayer.Values.AltColYPos)
    // : 0.5f);
    // Func2145738(_field1048);
    // }
}

void PlayerAiData::func2144B88(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // if (!Flags2.TestFlag(AiFlags2.TargetPlayer))
    // {
    // return;
    // }
    // Debug.Assert(_targetPlayer != null);
    // Vector3 toTarget = _targetPlayer.Position - _player.Position;
    // float targetDist = toTarget.Length;
    // if (_field1020 == 0 || Vector3.Dot(toTarget, _player._facingVector) < 0)
    // {
    // _targetPlayer.GetPosition(out Vector3 targetPos);
    // int prevField1020 = _field1020;
    // if (Flags2.TestFlag(AiFlags2.Bit21))
    // {
    // _field1020 = 0;
    // }
    // if (_player.BotLevel == 0)
    // {
    // _field1020 = 15 * 2;
    // }
    // else if (_player.BotLevel == 1)
    // {
    // _field1020 = 7 * 2;
    // }
    // else
    // {
    // _field1020 = 3 * 2;
    // }
    // if (_field1020 < _player._disruptedTimer)
    // {
    // _field1020 += (int)Rng.GetRandomInt2(_player._disruptedTimer - _field1020);
    // }
    // int field1020Diff = _field1020 - prevField1020;
    // if (Flags4.TestFlag(AiFlags4.Bit3) && field1020Diff > 0 && _player.BotLevel > 0)
    // {
    // EquipInfo equip = _player.EquipInfo;
    // WeaponInfo weapon = equip.Weapon;
    // bool isCharged = false;
    // float chargePct = 0;
    // if (weapon.Flags.TestFlag(WeaponFlags.PartialCharge))
    // {
    // if (weapon.Flags.TestFlag(WeaponFlags.CanCharge)
    // && equip.ChargeLevel >= weapon.MinCharge * 2)
    // {
    // isCharged = true;
    // chargePct = (equip.ChargeLevel - weapon.MinCharge * 2) / (float)(weapon.FullCharge * 2 - weapon.MinCharge * 2);
    // }
    // }
    // else if (equip.ChargeLevel >= weapon.FullCharge * 2)
    // {
    // isCharged = true;
    // chargePct = 1;
    // }
    // Vector3 vec = (targetPos - _field1054) / (field1020Diff / 2f);
    // float homing;
    // float speed;
    // if (isCharged)
    // {
    // homing = (weapon.MinChargeHoming
    // + ((weapon.ChargedHoming - weapon.MinChargeHoming) * chargePct)) / 4096f / 2;
    // speed = (weapon.MinChargeSpeed
    // + ((weapon.ChargedSpeed - weapon.MinChargeSpeed) * chargePct)) / 4096f / 2;
    // }
    // else
    // {
    // homing = weapon.UnchargedHoming / 4096f / 2;
    // speed = weapon.UnchargedSpeed / 4096f / 2;
    // }
    // if (homing > 0 || speed <= 0)
    // {
    // vec *= (_field1020 / 2f) / 2f;
    // }
    // else
    // {
    // Vector3 muzzleTarget = targetPos - _player._muzzlePos;
    // float muzzleDist = muzzleTarget.Length;
    // vec *= muzzleDist;
    // ushort decay = weapon.SpeedDecayTimes[isCharged ? 1 : 0];
    // float finalSpeed;
    // if (decay == 0)
    // {
    // finalSpeed = speed;
    // }
    // else if (isCharged)
    // {
    // finalSpeed = (weapon.MinChargeFinalSpeed
    // + ((weapon.ChargedFinalSpeed - weapon.MinChargeFinalSpeed) * chargePct)) / 4096f / 2;
    // }
    // else
    // {
    // finalSpeed = weapon.UnchargedFinalSpeed / 4096f / 2;
    // }
    // vec /= finalSpeed;
    // }
    // _field1048 = targetPos + vec;
    // }
    // else
    // {
    // _field1048 = targetPos;
    // }
    // _field1054 = targetPos;
    // Flags4 |= AiFlags4.Bit3;
    // _field1048 = _field1048.AddY(_targetPlayer.IsAltForm ? Fixed.ToFloat(_targetPlayer.Values.AltColYPos) : 0.5f);
    // Vector3 speedDiff = _player.Speed - _targetPlayer.Speed;
    // var camVec = new Vector3(_player.CameraInfo.Field50, 0, _player.CameraInfo.Field54);
    // float dot1 = MathF.Abs(Vector3.Dot(speedDiff, camVec));
    // float dot2 = MathF.Abs(Vector3.Dot(speedDiff, _player.CameraInfo.UpVector));
    // float v52;
    // float v66;
    // if (_player.BotLevel == 0)
    // {
    // v52 = (dot1 * 5) + 0.25f;
    // v66 = (dot2 * 5) + 0.25f;
    // if (!Flags4.TestFlag(AiFlags4.Bit2))
    // {
    // v52 += targetDist / 2;
    // v66 += targetDist / 2;
    // }
    // }
    // else if (_player.BotLevel == 1)
    // {
    // v52 = (dot1 * 2) + 0.1f;
    // v66 = (dot2 * 2) + 0.1f;
    // if (!Flags4.TestFlag(AiFlags4.Bit2))
    // {
    // v52 += targetDist / 9;
    // v66 += targetDist / 9;
    // }
    // }
    // else
    // {
    // v52 = (dot1 * 0.2f) + 0.01f;
    // v66 = (dot2 * 0.2f) + 0.01f;
    // if (!Flags4.TestFlag(AiFlags4.Bit2))
    // {
    // v52 += targetDist / 50;
    // v66 += targetDist / 50;
    // }
    // }
    // if (_player._disruptedTimer > 0)
    // {
    // v52 *= 2;
    // v66 *= 2;
    // }
    // if (Flags2.TestFlag(AiFlags2.Bit21))
    // {
    // v52 /= 2;
    // v66 /= 2;
    // }
    // if (_player.ShockCoilTimer > 10 * 2)
    // {
    // v52 /= 2;
    // v66 /= 2;
    // }
    // int v61 = (int)(v52 * 4096);
    // int v62 = (int)(v66 * 4096);
    // float rand1 = (Rng.GetRandomInt2(v61 * 2) - v61) / 4096f;
    // float rand2 = (Rng.GetRandomInt2(v62 * 2) - v62) / 4096f;
    // if (_player._disruptedTimer == 0)
    // {
    // if (rand1 > 6)
    // {
    // rand1 = Rng.GetRandomInt2(8192) / 4096f + 4;
    // }
    // else if (rand1 < -6)
    // {
    // rand1 = -4 - Rng.GetRandomInt2(9182) / 4096f;
    // }
    // if (rand2 > 6)
    // {
    // rand2 = Rng.GetRandomInt2(8192) / 4096f + 4;
    // }
    // else if (rand2 < -6)
    // {
    // rand2 = -4 - Rng.GetRandomInt2(9182) / 4096f;
    // }
    // }
    // _field1048 += camVec * rand1 + _player.CameraInfo.UpVector * rand2;
    // }
    // Func2145738(_field1048);
    // if (Flags4.TestFlag(AiFlags4.Bit2))
    // {
    // float aimValue = _aimValues[_player.BotLevel] / 2;
    // _buttonAimX = Math.Clamp(_buttonAimX, -aimValue, aimValue);
    // _buttonAimY = Math.Clamp(_buttonAimY, -aimValue, aimValue);
    // }
}

void PlayerAiData::func2145BA0(
    const gameplay::Session& session,
    std::uint8_t bot_slot) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    // NOT PORTED.  The managed body has lines the converter did not
    // understand, or calls something that is itself not ported, and a
    // half-converted behaviour would run the parts it did understand
    // without the parts it did not.  The managed source follows.
    // float facingY = _player._facingVector.Y;
    // if (facingY != 0)
    // {
    // float aimY = MathHelper.RadiansToDegrees(MathF.Acos(facingY)) - 90;
    // float value = _aimValues[_player.BotLevel];
    // _buttonAimY = Math.Clamp(aimY, -value, value);
    // }
}

void PlayerAiData::func214715C(
    const gameplay::Session& session,
    std::uint8_t bot_slot,
    AiContext& context) noexcept {
    static_cast<void>(session);
    static_cast<void>(bot_slot);
    static_cast<void>(context);
    context.field4 = 0;
    context.field5 = 0;
    context.field6 = 0;
    context.field7 = 0;
    context.field8 = 0;
    context.field9 = 0;
    context.fielda = 0;
    context.fieldb = 0;
    context.fieldc = 0;
    context.fieldd = 28;
    context.fielde = 0;
    context.fieldf = 0;
    switch (context.func24_id)
    {
        case 2:
        context.fielda = 31;
        context.fieldb = 4;
        break;
        case 3:
        context.fielda = 31;
        context.fieldb = 4;
        context.fieldd = 29;
        break;
        case 4:
        context.fielda = 32;
        context.fieldb = 4;
        break;
        case 5:
        context.fielda = 32;
        context.fieldb = 4;
        context.fielde = 38;
        break;
        case 6:
        context.fielda = 32;
        context.fieldb = 3;
        break;
        case 7:
        context.fielda = 32;
        context.fieldb = 25;
        break;
        case 8:
        context.fielda = 32;
        context.fieldb = 26;
        break;
        case 9:
        context.field4 = 37;
        break;
        case 10:
        context.field4 = 37;
        context.fielde = 38;
        break;
        case 11:
        context.field4 = 33;
        context.field9 = 39;
        break;
        case 12:
        context.field4 = 33;
        context.field9 = 39;
        context.fieldd = 29;
        break;
        case 13:
        context.field4 = 33;
        context.field9 = 39;
        context.field6 = 51;
        break;
        case 14:
        context.field4 = 33;
        context.field9 = 4;
        break;
        case 15:
        context.field4 = 33;
        context.field9 = 4;
        context.fieldd = 29;
        break;
        case 16:
        context.field4 = 37;
        context.field9 = 4;
        break;
        case 17:
        context.field4 = 33;
        context.field9 = 4;
        context.fielde = 38;
        context.fielda = 32;
        context.fieldb = 4;
        break;
        case 18:
        context.field4 = 37;
        context.field9 = 4;
        context.fielde = 38;
        break;
        case 19:
        context.fielda = 32;
        context.fieldb = 4;
        context.field4 = 37;
        context.field9 = 4;
        break;
        case 20:
        context.field4 = 37;
        context.field9 = 4;
        context.field5 = 47;
        break;
        case 21:
        context.field4 = 37;
        context.field9 = 4;
        context.fieldd = 29;
        break;
        case 22:
        context.field4 = 37;
        context.field9 = 4;
        context.fieldd = 29;
        if (bot_level_ > 0)
        {
            context.field5 = 48;
        }
        break;
        case 23:
        context.field4 = 37;
        context.field9 = 24;
        context.fieldd = 29;
        break;
        case 24:
        context.field4 = 37;
        context.field9 = 24;
        context.fieldd = 29;
        context.fieldc = 63;
        context.fieldf = 69;
        break;
        case 25:
        context.field4 = 37;
        context.field9 = 12;
        context.fieldd = 29;
        break;
        case 26:
        context.field4 = 37;
        context.field9 = 12;
        context.field5 = 47;
        context.fieldd = 29;
        break;
        case 27:
        context.field4 = 37;
        context.field9 = 13;
        context.fieldd = 29;
        break;
        case 28:
        context.field4 = 37;
        context.field9 = 12;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 66;
        break;
        case 29:
        context.field4 = 37;
        context.field9 = 4;
        context.field5 = 47;
        context.fieldd = 29;
        break;
        case 30:
        context.field4 = 37;
        context.field9 = 4;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 64;
        break;
        case 31:
        context.field4 = 33;
        context.field9 = 4;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 64;
        break;
        case 32:
        context.field4 = 33;
        context.field9 = 4;
        context.fieldd = 29;
        if (bot_level_ > 0)
        {
            context.field5 = 48;
        }
        context.fieldf = 64;
        break;
        case 33:
        context.field4 = 37;
        context.field9 = 4;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 65;
        break;
        case 34:
        context.field4 = 37;
        context.field9 = 4;
        context.fieldd = 29;
        context.fieldc = 63;
        context.fieldf = 65;
        break;
        case 35:
        context.field4 = 33;
        context.field9 = 4;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 65;
        break;
        case 36:
        context.field4 = 33;
        context.field9 = 4;
        context.fieldd = 29;
        context.fieldc = 63;
        context.fieldf = 65;
        break;
        case 37:
        context.field4 = 37;
        context.field9 = 4;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 66;
        break;
        case 38:
        context.field4 = 33;
        context.field9 = 4;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 66;
        break;
        case 39:
        context.field4 = 37;
        context.field9 = 4;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 67;
        break;
        case 40:
        context.field4 = 33;
        context.field9 = 4;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 67;
        break;
        case 41:
        context.field4 = 34;
        context.field9 = 4;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 67;
        break;
        case 42:
        context.field4 = 37;
        context.field5 = 47;
        context.field9 = 24;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 65;
        break;
        case 43:
        context.field4 = 37;
        context.field5 = 47;
        context.field9 = 24;
        context.fieldd = 29;
        context.fieldc = 63;
        context.fieldf = 65;
        break;
        case 44:
        context.fielda = 31;
        context.fieldb = 4;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 68;
        break;
        case 45:
        context.field4 = 33;
        context.field9 = 4;
        context.fielda = 31;
        context.fieldb = 4;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 69;
        break;
        case 48:
        context.fielda = 31;
        context.fieldb = 4;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 70;
        break;
        case 50:
        context.field4 = 37;
        context.field9 = 40;
        break;
        case 51:
        context.field4 = 37;
        context.field9 = 24;
        break;
        case 52:
        context.field4 = 37;
        context.field9 = 24;
        context.fieldc = 56;
        break;
        case 53:
        context.field4 = 37;
        context.field9 = 44;
        break;
        case 54:
        context.field4 = 37;
        context.field9 = 44;
        context.fieldc = 56;
        break;
        case 55:
        context.fielda = 32;
        context.fieldb = 27;
        context.field4 = 37;
        context.field9 = 44;
        field_b8_ = {29.0F, 15.0F, 0.0F};
        break;
        case 56:
        context.field4 = 37;
        context.field9 = 45;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 65;
        break;
        case 57:
        context.fielda = 32;
        context.fieldb = 4;
        context.field4 = 37;
        context.field9 = 46;
        break;
        case 59:
        context.field4 = 37;
        context.field9 = 6;
        break;
        case 60:
        context.field4 = 37;
        context.field9 = 6;
        context.fieldc = 56;
        break;
        case 61:
        context.field4 = 37;
        context.field9 = 6;
        context.field8 = 7;
        break;
        case 62:
        context.field4 = 37;
        context.field9 = 6;
        context.fieldc = 56;
        context.field8 = 7;
        break;
        case 63:
        context.field4 = 37;
        context.field9 = 6;
        context.field8 = 7;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 65;
        break;
        case 64:
        context.field4 = 37;
        context.field9 = 6;
        context.field8 = 8;
        break;
        case 65:
        context.field4 = 37;
        context.field9 = 6;
        context.field8 = 9;
        break;
        case 66:
        context.field4 = 37;
        context.field9 = 6;
        context.field8 = 10;
        break;
        case 67:
        context.field4 = 37;
        context.field9 = 6;
        context.field8 = 11;
        break;
        case 68:
        context.field4 = 37;
        context.field9 = 14;
        break;
        case 69:
        context.field4 = 37;
        context.field9 = 14;
        context.fieldc = 56;
        break;
        case 70:
        context.field4 = 37;
        context.field9 = 15;
        break;
        case 71:
        context.field4 = 37;
        context.field9 = 15;
        context.fieldc = 56;
        break;
        case 72:
        context.field4 = 37;
        context.field9 = 16;
        break;
        case 73:
        context.field4 = 37;
        context.field9 = 16;
        context.fieldc = 56;
        break;
        case 74:
        context.field4 = 37;
        context.field9 = 16;
        context.fieldc = 56;
        context.field6 = 52;
        break;
        case 75:
        context.field4 = 37;
        context.field9 = 16;
        context.fielda = 32;
        context.fieldb = 4;
        break;
        case 76:
        context.field4 = 37;
        context.field9 = 23;
        break;
        case 77:
        context.field4 = 37;
        context.field9 = 23;
        context.fieldc = 56;
        break;
        case 78:
        context.field4 = 33;
        context.field9 = 23;
        break;
        case 82:
        context.field4 = 33;
        context.field9 = 6;
        break;
        case 83:
        context.field4 = 33;
        context.field9 = 6;
        context.fieldc = 56;
        break;
        case 84:
        context.field4 = 33;
        context.field9 = 6;
        context.field8 = 7;
        break;
        case 85:
        context.field4 = 33;
        context.field9 = 6;
        context.field8 = 7;
        context.fieldd = 29;
        context.fieldc = 62;
        context.fieldf = 65;
        break;
        case 86:
        context.field4 = 33;
        context.field9 = 6;
        context.field8 = 8;
        break;
        case 87:
        context.field4 = 33;
        context.field9 = 6;
        context.field8 = 9;
        break;
        case 88:
        context.field4 = 33;
        context.field9 = 6;
        context.field8 = 10;
        break;
        case 89:
        context.field4 = 33;
        context.field9 = 6;
        context.field8 = 11;
        break;
        case 90:
        context.field4 = 33;
        context.field9 = 20;
        break;
        case 91:
        context.field4 = 33;
        context.field9 = 17;
        break;
        case 92:
        context.field4 = 33;
        context.field9 = 15;
        break;
        case 93:
        context.field4 = 33;
        context.field9 = 15;
        context.fieldc = 56;
        break;
        case 94:
        context.field4 = 33;
        context.field9 = 19;
        break;
        case 95:
        context.fielda = 32;
        context.fieldb = 26;
        break;
        case 96:
        context.fieldc = 55;
        field_b8_ = {29.0F, 15.0F, 0.0F};
        break;
        case 97:
        context.fieldc = 56;
        break;
        case 98:
        context.fieldc = 57;
        break;
        case 101:
        context.fieldc = 59;
        break;
        case 103:
        context.fieldc = 61;
        break;
        case 106:
        context.field4 = 33;
        context.field9 = 4;
        context.fieldc = 56;
        break;
        case 108:
        context.field4 = 37;
        context.field9 = 4;
        context.fieldc = 56;
        break;
        case 109:
        context.field4 = 37;
        context.field9 = 42;
        context.fieldc = 56;
        break;
        case 110:
        context.field4 = 37;
        context.field9 = 42;
        context.fieldc = 56;
        context.field5 = 47;
        context.field6 = 51;
        break;
        case 112:
        context.field4 = 37;
        context.field5 = 47;
        context.field9 = 4;
        context.fieldc = 56;
        break;
        case 113:
        context.field4 = 37;
        context.field5 = 47;
        context.field9 = 5;
        context.fieldc = 60;
        break;
        case 115:
        context.field4 = 37;
        context.field9 = 12;
        break;
        case 116:
        context.field4 = 37;
        context.field9 = 12;
        context.fielda = 32;
        context.fieldb = 4;
        break;
        case 117:
        context.field4 = 37;
        context.field9 = 12;
        context.fieldc = 56;
        break;
        case 118:
        context.field4 = 37;
        context.field9 = 12;
        context.fieldc = 56;
        context.field6 = 52;
        break;
        case 119:
        context.field4 = 37;
        context.field9 = 6;
        context.fieldd = 29;
        break;
        case 120:
        context.field4 = 33;
        context.field9 = 6;
        context.fieldd = 29;
        break;
        case 121:
        context.field4 = 33;
        context.field9 = 35;
        break;
        case 122:
        context.field4 = 33;
        context.field9 = 36;
        break;
        default:
        break;
    }
    if ((bot_level_ == 0) && (context.field5 == 47))
    {
        context.field5 = 0;
    }
    if (context.field4 != 37)
    {
        flags2_ = without(flags2_, AiFlags2::Bit7);
    }
}

} // namespace fruityprime::players
