#!/usr/bin/env python3
"""Generate PlayerAi's ExecuteFuncs dispatchers from PlayerAi.cs.

The three dispatchers are switches over a couple of hundred case labels,
several of them C# range patterns (`case >= 2 and <= 44:`).  Retyping those by
hand is how a bot ends up running the wrong behaviour for one value in the
middle of a range, with nothing to show for it but a bot that plays slightly
oddly.  They are generated instead.

    python tools/gen-ai-dispatch.py            # write the dispatchers
    python tools/gen-ai-dispatch.py --list     # just name the leaf functions

Writes src/MphRead.Native/Entities/Players/ai_dispatch.generated.hpp.
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = (ROOT / "src" / "MphRead" / "Entities" / "Players" / "PlayerAi.cs")
OUTPUT = (ROOT / "src" / "MphRead.Native" / "Entities" / "Players"
          / "ai_dispatch.generated.hpp")

DISPATCHERS = [
    ("ExecuteFuncs1", "funcs1", "execute_funcs1"),
    ("ExecuteFuncs2", "funcs2", "execute_funcs2"),
    ("ExecuteFuncs4", "funcs4", "execute_funcs4"),
]

RANGE = re.compile(r"case\s*>=\s*(\d+)\s*and\s*<=\s*(\d+)\s*:")
SINGLE = re.compile(r"case\s+(\d+)\s*:")
CALL = re.compile(r"(\w+)\(context\);|(\w+)\(\);")


def method_body(text: str, name: str) -> str:
    at = text.index("private void %s(" % name)
    start = text.index("{", at)
    depth = 0
    index = start
    while True:
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                break
        index += 1
    return text[start:index]


def snake(name: str) -> str:
    """Func1_214A39C -> func1_214A39C; Func1_SetInvulnerable -> the same."""
    return name[0].lower() + name[1:]


def parse(body: str) -> list[tuple[list[int], str | None]]:
    """Case labels grouped with the function they call, in source order."""
    groups: list[tuple[list[int], str | None]] = []
    pending: list[int] = []
    for line in body.splitlines():
        stripped = line.strip()
        matched = RANGE.search(stripped)
        if matched:
            pending.extend(range(int(matched.group(1)),
                                 int(matched.group(2)) + 1))
            continue
        matched = SINGLE.search(stripped)
        if matched:
            pending.append(int(matched.group(1)))
            continue
        if stripped == "break;" and pending:
            groups.append((pending, None))
            pending = []
            continue
        matched = CALL.search(stripped)
        if matched and pending:
            groups.append((pending, matched.group(1) or matched.group(2)))
            pending = []
    return groups


def main(argv: list[str]) -> int:
    text = SOURCE.read_text(encoding="utf-8")
    parsed = {name: parse(method_body(text, name))
              for name, _, _ in DISPATCHERS}

    leaves: dict[str, set[str]] = {}
    for name, _, _ in DISPATCHERS:
        leaves[name] = {call for _, call in parsed[name] if call}

    if "--list" in argv:
        for name, _, _ in DISPATCHERS:
            print("%s: %d cases, %d distinct functions"
                  % (name, sum(len(labels) for labels, _ in parsed[name]),
                     len(leaves[name])))
            for call in sorted(leaves[name]):
                print("   ", call)
        return 0

    lines = [
        "#pragma once",
        "",
        "// Generated by tools/gen-ai-dispatch.py from",
        "// src/MphRead/Entities/Players/PlayerAi.cs.  Do not edit by hand.",
        "//",
        "// PlayerAi.ExecuteFuncs1, ExecuteFuncs2 and ExecuteFuncs4 as case",
        "// tables: which behaviour each identifier runs.  The managed",
        "// dispatchers use C# range patterns, which are expanded here so a",
        "// value in the middle of a range cannot go missing.",
        "",
        "#include <cstdint>",
        "",
        "namespace fruityprime::players::ai_dispatch {",
        "",
        "// A behaviour is named by its index in the list below; 0 means the",
        "// identifier runs nothing, which is a real case rather than a hole.",
        "enum class Behavior : std::uint8_t { None = 0 };",
        "",
    ]
    for name, prefix, _ in DISPATCHERS:
        groups = parsed[name]
        names = sorted(leaves[name])
        index_of = {call: position + 1
                    for position, call in enumerate(names)}
        highest = max((label for labels, _ in groups for label in labels),
                      default=0)
        table = [0] * (highest + 1)
        for labels, call in groups:
            for label in labels:
                table[label] = index_of[call] if call else 0
        lines.append("// %s: %d identifiers, %d distinct behaviours."
                     % (name, highest + 1, len(names)))
        lines.append("inline constexpr const char* %s_names[] = {" % prefix)
        lines.append('    "",  // 0: runs nothing')
        for position, call in enumerate(names):
            lines.append('    "%s",  // %d' % (call, position + 1))
        lines.append("};")
        lines.append("")
        lines.append("inline constexpr std::uint8_t %s_table[] = {" % prefix)
        for start in range(0, len(table), 16):
            row = ", ".join(str(value)
                            for value in table[start:start + 16])
            lines.append("    %s," % row)
        lines.append("};")
        lines.append("")
    lines += ["} // namespace fruityprime::players::ai_dispatch", ""]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\r\n")
    for name, _, _ in DISPATCHERS:
        print("%s: %d distinct behaviours" % (name, len(leaves[name])))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
