include("${CMAKE_CURRENT_LIST_DIR}/FruityNativeConfig.cmake")

if(NOT DEFINED OUTPUT_FILE OR OUTPUT_FILE STREQUAL "")
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

string(JOIN " " _fruity_android_abis ${FRUITY_ANDROID_ABIS})
file(APPEND "${OUTPUT_FILE}" "ANDROID_COMPILE_SDK=${FRUITY_ANDROID_COMPILE_SDK}\n")
file(APPEND "${OUTPUT_FILE}" "ANDROID_MIN_API=${FRUITY_ANDROID_MIN_API}\n")
file(APPEND "${OUTPUT_FILE}" "ANDROID_BUILD_TOOLS=${FRUITY_ANDROID_BUILD_TOOLS}\n")
file(APPEND "${OUTPUT_FILE}" "ANDROID_NDK_VERSION=${FRUITY_ANDROID_NDK_VERSION}\n")
file(APPEND "${OUTPUT_FILE}" "FRUITY_ANDROID_ABIS=${_fruity_android_abis}\n")
